/**
 * OBI-One Electrophysiology Metrics tool.
 * Translated from: backend/src/neuroagent/tools/obione_ephysmetrics_getone.py
 */

import { z } from 'zod';
import { HTTPError } from 'ky';
import { BaseTool } from '../base-tool';
import { ObiOneContextVariables } from './types';
import {
  zElectrophysiologyrecordingMetricsEndpointDeclaredElectrophysiologyrecordingMetricsTraceIdGetData,
  zElectrophysiologyMetricsOutput,
} from '../autogenerated_types/obione/zod.gen';

/**
 * Input schema for the electrophysiology metrics tool.
 * Extends the autogenerated schema with overridden field descriptions.
 */
const EphysMetricsGetOneInputSchema =
  zElectrophysiologyrecordingMetricsEndpointDeclaredElectrophysiologyrecordingMetricsTraceIdGetData.shape.path
    .extend({
      trace_id: z
        .string()
        .uuid()
        .describe(
          'Id of the electrical cell recording from which features must be computed.'
        ),
    })
    .merge(
      zElectrophysiologyrecordingMetricsEndpointDeclaredElectrophysiologyrecordingMetricsTraceIdGetData.shape.query
        .unwrap()
    );

/**
 * Tool to compute electrophysiology metrics.
 */
export class EphysMetricsGetOneTool extends BaseTool<
  typeof EphysMetricsGetOneInputSchema,
  ObiOneContextVariables
> {
  static toolName = 'obione-ephysmetrics-getone';
  static toolDescription =
    'Given an electrical cell recording ID, fetch data about the electrophysiological features. ' +
    'This is the correct way to compute electrical recording metrics — do NOT download the asset + Python to extract metrics. ' +
    'This tool already handles asset processing internally.';

  static toolNameFrontend = 'Compute Electrophysiology Metrics';
  static toolDescriptionFrontend =
    'Analyze detailed electrophysiological features of neuron recordings. This tool allows you to:\n' +
    '• Measure various electrophysiological properties\n' +
    '• Calculate statistical metrics from recordings\n' +
    '• Analyze specific electrical characteristics of neurons\n\n' +
    'Provide an electrical cell recording ID to compute its detailed electrophysiological features.';

  static utterances = [
    'Analyze electrophysiological features',
    'Compute metrics for this recording',
    'Get electrophysiology data',
    'Calculate the spike count for this trace',
    'Count spikes using the step protocol',
    'Run a full analysis of this trace using all available metrics',
    'Get spike count from step protocol between 0.1 and 0.3 nA',
  ];

  override contextVariables: ObiOneContextVariables;
  override inputSchema = EphysMetricsGetOneInputSchema;

  constructor(contextVariables: ObiOneContextVariables) {
    super();
    this.contextVariables = contextVariables;
  }

  /**
   * Run the electrophysiology feature extraction logic.
   */
  async execute(
    input: z.infer<typeof EphysMetricsGetOneInputSchema>
  ): Promise<z.infer<typeof zElectrophysiologyMetricsOutput>> {
    const { obiOneUrl, vlabId, projectId, httpClient } = this.contextVariables;

    // Prepare headers
    const headers: Record<string, string> = {};
    if (vlabId) {
      headers['virtual_lab_id'] = vlabId;
    }
    if (projectId) {
      headers['project_id'] = projectId;
    }

    // Prepare query params (exclude trace_id which goes in the path)
    // Note: We use URLSearchParams to properly handle arrays as repeated parameters
    // (e.g., param=val1&param=val2) instead of comma-separated (param=val1,val2)
    // This matches the Python backend's httpx behavior
    const searchParams = new URLSearchParams();
    const { trace_id, ...restParams } = input;

    // Use trace_id from path
    const recordingId = trace_id;

    // Add remaining query params
    // Arrays are added as repeated parameters to match httpx behavior
    Object.entries(restParams).forEach(([key, value]) => {
      if (value !== undefined && value !== null) {
        if (Array.isArray(value)) {
          // Add each array element as a separate parameter
          value.forEach((item) => searchParams.append(key, String(item)));
        } else {
          searchParams.append(key, String(value));
        }
      }
    });

    try {
      const response = await httpClient
        .get(
          `${obiOneUrl}/declared/electrophysiologyrecording-metrics/${recordingId}`,
          {
            headers,
            searchParams,
          }
        )
        .json();

      // Validate response with Zod schema
      return zElectrophysiologyMetricsOutput.parse(response);
    } catch (error) {
      if (error instanceof HTTPError) {
        const { status, statusText } = error.response;
        let responseBody = '';
        try {
          responseBody = await error.response.text();
        } catch {
          // Ignore if we can't read the body
        }
        throw new Error(
          `The electrophysiology metrics endpoint returned a non 200 response code. Error: ${status} ${statusText}${responseBody ? ': ' + responseBody : ''}`
        );
      }
      throw error;
    }
  }

  /**
   * Check if the tool is online.
   */
  static async isOnline(contextVariables: ObiOneContextVariables): Promise<boolean> {
    try {
      const { obiOneUrl, httpClient } = contextVariables;
      const healthUrl = `${obiOneUrl.replace(/\/$/, '')}/health`;

      await httpClient.get(healthUrl);
      return true;
    } catch {
      return false;
    }
  }
}
