/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/thumbnail-generation/core/cell-morphology/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Morphology Preview
         * @description Generate a preview of a morphology
         *
         *     Args:
         *         entity_id: The ID of the entity
         *         asset_id: The ID of the asset
         *         dpi: The DPI of the preview
         *         context: The context of the request
         *
         *     Returns:
         *         A response containing the preview of the morphology
         */
        get: operations["get_morphology_preview_api_thumbnail_generation_core_cell_morphology_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thumbnail-generation/core/electrical-cell-recording/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ephys Preview
         * @description Generate a preview of an ephys trace.
         *
         *     Args:
         *         entity_id: The ID of the entity
         *         asset_id: The ID of the asset
         *         dpi: The DPI of the preview
         *         context: The context of the request
         *
         *     Returns:
         *         A response containing the preview of the ephys trace
         */
        get: operations["get_ephys_preview_api_thumbnail_generation_core_electrical_cell_recording_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thumbnail-generation/core/ion-channel-recording/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ion Channel Recording Preview
         * @description Generate a preview of an ion_channel_recording trace.
         *
         *     Args:
         *         entity_id: The ID of the entity
         *         asset_id: The ID of the asset
         *         dpi: The DPI of the preview
         *         context: The context of the request
         *
         *     Returns:
         *         A response containing the preview of the ion_channel_recording trace
         */
        get: operations["get_ion_channel_recording_preview_api_thumbnail_generation_core_ion_channel_recording_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thumbnail-generation/core/model-trace/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Model Trace Preview
         * @description Generate a preview of a model trace
         *
         *     Args:
         *         entity_id: The ID of the entity
         *         context: The context of the request
         *
         *     Returns:
         *         A response containing the preview of the model trace
         */
        get: operations["get_model_trace_preview_api_thumbnail_generation_core_model_trace_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thumbnail-generation/core/{simulation_type}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Simulation Plot
         * @description Generate a preview of a simulation
         *
         *     Args:
         *         entity_id: The ID of the entity
         *         asset_id: The ID of the asset
         *         simulation_type: Type of simulation
         *         target: Plot target
         *         w: Width of the generated image
         *         h: Height of the generated image
         *         context: The context of the request
         *
         *     Returns:
         *         A response containing the plot of the simulation target
         */
        get: operations["get_simulation_plot_api_thumbnail_generation_core__simulation_type__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thumbnail-generation/generate/morphology-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Morphology Image
         * @description Endpoint to get a preview image of a morphology.
         *     Sample Content URL:
         *     https://bbp.epfl.ch/nexus/v1/files/bbp/mouselight/https%3A%2F%2Fbbp.epfl.ch%2Fnexus%2Fv1%2Fresources%2Fbbp%2Fmouselight%2F_%2F0befd25c-a28a-4916-9a8a-adcd767db118
         */
        get: operations["get_morphology_image_api_thumbnail_generation_generate_morphology_image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thumbnail-generation/generate/trace-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trace Image
         * @description Endpoint to get a preview image of an electrophysiology trace
         *     Sample Content URL:
         *     https://bbp.epfl.ch/nexus/v1/files/public/hippocampus/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2Fb67a2aa6-d132-409b-8de5-49bb306bb251
         */
        get: operations["get_trace_image_api_thumbnail_generation_generate_trace_image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thumbnail-generation/generate/simulation-plot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Simulation Plot
         * @description Endpoint to get a preview image of an simulation plots
         *     Sample Content URL:
         *     https://sbo-nexus-delta.shapes-registry.org/v1/files/cad43d74-f697-48d6-9242-28cb6b4a4956/f9b265b2-22c3-4a92-9ad5-79dff37e39ca/https%3A%2F%2Fopenbrainplatform.org%2Fdata%2Fcad43d74-f697-48d6-9242-28cb6b4a4956%2Ff9b265b2-22c3-4a92-9ad5-79dff37e39ca%2Feadf0aa4-109c-4422-806c-325e5669565a?rev=1
         */
        get: operations["get_simulation_plot_api_thumbnail_generation_generate_simulation_plot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thumbnail-generation/soma/process-nexus-swc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Process Soma
         * @description Process the SWC file fetched from the given URL and return the generated mesh file.
         */
        get: operations["process_soma_api_thumbnail_generation_soma_process_nexus_swc_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thumbnail-generation/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Simple health check endpoint
         */
        get: operations["health_api_thumbnail_generation_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ErrorMessage
         * @description Model of an error message
         */
        ErrorMessage: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_morphology_preview_api_thumbnail_generation_core_cell_morphology_preview_get: {
        parameters: {
            query: {
                entity_id: string;
                asset_id: string;
                dpi?: number | null;
            };
            header?: {
                "virtual-lab-id"?: string | null;
                "project-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ephys_preview_api_thumbnail_generation_core_electrical_cell_recording_preview_get: {
        parameters: {
            query: {
                entity_id: string;
                asset_id: string;
                dpi?: number | null;
            };
            header?: {
                "virtual-lab-id"?: string | null;
                "project-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ion_channel_recording_preview_api_thumbnail_generation_core_ion_channel_recording_preview_get: {
        parameters: {
            query: {
                entity_id: string;
                asset_id: string;
                dpi?: number | null;
            };
            header?: {
                "virtual-lab-id"?: string | null;
                "project-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_trace_preview_api_thumbnail_generation_core_model_trace_preview_get: {
        parameters: {
            query: {
                entity_id: string;
            };
            header?: {
                "virtual-lab-id"?: string | null;
                "project-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_simulation_plot_api_thumbnail_generation_core__simulation_type__preview_get: {
        parameters: {
            query: {
                entity_id: string;
                asset_id: string;
                target: "stimulus" | "simulation";
                w?: number | null;
                h?: number | null;
            };
            header?: {
                "virtual-lab-id"?: string | null;
                "project-id"?: string | null;
            };
            path: {
                simulation_type: "single-neuron-simulation" | "single-neuron-synaptome-simulation";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_morphology_image_api_thumbnail_generation_generate_morphology_image_get: {
        parameters: {
            query: {
                content_url: string;
                dpi?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorMessage"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorMessage"];
                };
            };
        };
    };
    get_trace_image_api_thumbnail_generation_generate_trace_image_get: {
        parameters: {
            query: {
                content_url: string;
                dpi?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorMessage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_simulation_plot_api_thumbnail_generation_generate_simulation_plot_get: {
        parameters: {
            query: {
                content_url: string;
                target: "stimulus" | "simulation";
                w?: number | null;
                h?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorMessage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_soma_api_thumbnail_generation_soma_process_nexus_swc_get: {
        parameters: {
            query: {
                /** @description URL of the SWC file to process */
                content_url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_thumbnail_generation_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
