"""Base tool."""

import logging
from abc import ABC, abstractmethod
from typing import Any, ClassVar
from uuid import UUID

from httpx import AsyncClient
from pydantic import BaseModel, ConfigDict, Field
from pydantic.json_schema import SkipJsonSchema

logger = logging.getLogger(__name__)


class BaseMetadata(BaseModel):
    """Base class for metadata."""

    model_config = ConfigDict(extra="ignore", arbitrary_types_allowed=True)


class EntitycoreMetadata(BaseMetadata):
    """Metadata class for all Entitycore tools."""

    httpx_client: AsyncClient
    entitycore_url: str
    vlab_id: UUID | None
    project_id: UUID | None
    entity_frontend_url: str


class EntitycoreExcludeBRParams(BaseModel):
    """Exclude BR parameters that the model should not use in BR compatible EC endpoints.

    The within_brain_region_hierarchy_id parameter should not be provided directly by the user.
    The tool will automatically make an extra request to map the brain region ID from
    within_brain_region_brain_region_id to the corresponding hierarchy ID during query execution.

    All other fields in this class are excluded to prevent the LLM from using them directly.
    Instead, the LLM should be encouraged to use within_brain_region_brain_region_id when
    filtering by brain region. Note that excluding brain_region__id and brain_region__id__in
    means we cannot filter for entities exactly within a specific region, but this is an
    accepted trade-off since most use cases care about entities within a region's subtree.

    To find all fields that match this pattern, run:
    git grep -n -E ".*brain_region__(name|name__in|name__ilike|id|id__in|acronym|acronym__in):" src/neuroagent/tools/autogenerated_types/entitycore.py
    """

    brain_region__name: SkipJsonSchema[None] = Field(default=None, exclude=True)
    brain_region__name__in: SkipJsonSchema[None] = Field(default=None, exclude=True)
    brain_region__name__ilike: SkipJsonSchema[None] = Field(default=None, exclude=True)
    brain_region__id: SkipJsonSchema[None] = Field(default=None, exclude=True)
    brain_region__id__in: SkipJsonSchema[None] = Field(default=None, exclude=True)
    brain_region__acronym: SkipJsonSchema[None] = Field(default=None, exclude=True)
    brain_region__acronym__in: SkipJsonSchema[None] = Field(default=None, exclude=True)
    emodel__brain_region__name: SkipJsonSchema[None] = Field(default=None, exclude=True)
    emodel__brain_region__name__in: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    emodel__brain_region__name__ilike: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    emodel__brain_region__id: SkipJsonSchema[None] = Field(default=None, exclude=True)
    emodel__brain_region__id__in: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    emodel__brain_region__acronym: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    emodel__brain_region__acronym__in: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    me_model__brain_region__name: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    me_model__brain_region__name__in: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    me_model__brain_region__name__ilike: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    me_model__brain_region__id: SkipJsonSchema[None] = Field(default=None, exclude=True)
    me_model__brain_region__id__in: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    me_model__brain_region__acronym: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    me_model__brain_region__acronym__in: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    morphology__brain_region__name: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    morphology__brain_region__name__in: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    morphology__brain_region__name__ilike: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    morphology__brain_region__id: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    morphology__brain_region__id__in: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    morphology__brain_region__acronym: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    morphology__brain_region__acronym__in: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    synaptome__brain_region__name: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    synaptome__brain_region__name__in: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    synaptome__brain_region__name__ilike: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    synaptome__brain_region__id: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    synaptome__brain_region__id__in: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    synaptome__brain_region__acronym: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    synaptome__brain_region__acronym__in: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )

    within_brain_region_hierarchy_id: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )
    within_brain_region_ascendants: SkipJsonSchema[None] = Field(
        default=None, exclude=True
    )


class EntitycoreExcludeNameParams(BaseModel):
    """Exclude name parameters that the model should not use in name compatible EC endpoints.

    These parameters are excluded to maximize the probability of the LLM using semantic_search
    instead of direct name-based filtering.
    """

    name: SkipJsonSchema[None] = Field(default=None, exclude=True)
    name__in: SkipJsonSchema[None] = Field(default=None, exclude=True)
    name__ilike: SkipJsonSchema[None] = Field(default=None, exclude=True)


class BaseTool(BaseModel, ABC):
    """Base class for the tools."""

    name: ClassVar[str]
    name_frontend: ClassVar[str] = ""
    description: ClassVar[str]
    description_frontend: ClassVar[str] = ""
    utterances: ClassVar[list[str]] = []
    metadata: BaseMetadata
    input_schema: BaseModel
    hil: ClassVar[bool] = False
    json_schema: ClassVar[dict[str, Any] | None] = None

    @classmethod
    def pydantic_to_openai_schema(cls) -> dict[str, Any]:
        """Convert pydantic schema to OpenAI json."""
        if cls.json_schema is not None:
            parameters = cls.json_schema
        else:
            parameters = cls.__annotations__["input_schema"].model_json_schema()

        # The name and description are duplicated to accomodate for
        # models compatible with flat and nested JSON schema.
        # E.g. o3 is flattened JSON schema compatible only
        new_retval: dict[str, Any] = {
            "type": "function",
            "name": cls.name,
            "description": cls.description,
            "function": {
                "name": cls.name,
                "description": cls.description,
                "strict": False,
                "parameters": parameters,
            },
        }
        new_retval["function"]["parameters"]["additionalProperties"] = False

        return new_retval

    @abstractmethod
    async def arun(self) -> BaseModel:
        """Run the tool."""

    @classmethod
    async def is_online(cls) -> bool:
        """Check if the tool is online.

        By default, we assume the tool is online.
        This method can be overridden by the tool to check if it is online. All the parameters
        need to be inside the `get_healthcheck_variables` dependency.
        """
        return False
