"""Get Reconstruction Morpho tool."""

from typing import ClassVar, Literal

from httpx import AsyncClient
from pydantic import Field

from neuroagent.tools.autogenerated_types.entitycore import (
    ListResponseReconstructionMorphologyRead,
    ReadManyReconstructionMorphologyGetParametersQuery,
)
from neuroagent.tools.base_tool import BaseMetadata, BaseTool


class ReconstructionMorphologyGetAllInput(
    ReadManyReconstructionMorphologyGetParametersQuery
):
    """Inputs for the reconstruction morphology get all tool."""

    within_brain_region_brain_region_id: str | None = Field(  # type: ignore[assignment]
        default=None,
        description="ID of the brain region of interest in UUID format. To find the ID use the resolve-brain-region-tool first.",
    )
    within_brain_region_hierarchy_id: Literal[
        "e3e70682-c209-4cac-a29f-6fbed82c07cd"
    ] = Field(  # type: ignore[assignment]
        default="e3e70682-c209-4cac-a29f-6fbed82c07cd",
        description="The hierarchy ID for brain regions. This is fixed to ensure consistent results.",
    )


class ReconstructionMorphologyGetAllMetadata(BaseMetadata):
    """Metadata class for ReconstructionMorphologyGetAllTool."""

    httpx_client: AsyncClient
    entitycore_url: str
    vlab_id: str | None
    project_id: str | None


class ReconstructionMorphologyGetAllTool(BaseTool):
    """Class defining the Get Reconstruction Morpho logic."""

    name: ClassVar[str] = "entitycore-reconstructionmorphology-getall"
    name_frontend: ClassVar[str] = "Get All Reconstruction Morphologies"
    description: ClassVar[
        str
    ] = """Searches a neuroscience based knowledge graph to retrieve reconstruction morphologies.
    Requires a 'brain_region_id' which is the ID of the brain region of interest as registered in the knowledge graph.
    Optionally accepts an mtype_id.
    The output is a list of morphologies, containing:
    - The brain region ID.
    - The brain region name.
    - The subject species name.
    - The morphology ID (it is the `id` field in the response - ignore other IDs).
    - The morphology name.
    - the morphology description.

    We explicitly exclude the assets and the legacy id but you can access them using the Get One Morphology tool.
    """
    description_frontend: ClassVar[
        str
    ] = """Search and retrieve neuron morphologies. Use this tool to:
    • Find neurons in specific brain regions
    • Search by morphology type
    • Access detailed morphological data

    Specify brain region and optional criteria to find relevant morphologies."""
    metadata: ReconstructionMorphologyGetAllMetadata
    input_schema: ReconstructionMorphologyGetAllInput

    async def arun(self) -> ListResponseReconstructionMorphologyRead:
        """From a brain region ID, extract morphologies.

        Returns
        -------
            list of KnowledgeGraphOutput to describe the morphology and its metadata, or an error dict.
        """
        query_params = self.input_schema.model_dump(exclude_defaults=True, mode="json")
        query_params["within_brain_region_hierarchy_id"] = (
            "e3e70682-c209-4cac-a29f-6fbed82c07cd"  # we need to explicitly add this since we exclude defaults
        )

        headers: dict[str, str] = {}
        if self.metadata.vlab_id is not None:
            headers["virtual-lab-id"] = self.metadata.vlab_id
        if self.metadata.project_id is not None:
            headers["project-id"] = self.metadata.project_id

        response = await self.metadata.httpx_client.get(
            url=self.metadata.entitycore_url.rstrip("/") + "/reconstruction-morphology",
            headers=headers,
            params=query_params,
        )
        if response.status_code != 200:
            raise ValueError(
                f"The morphology endpoint returned a non 200 response code. Error: {response.text}"
            )

        response_data = response.json()
        # Set assets and legacy_id to empty lists for each morphology
        for morphology in response_data["data"]:
            morphology["assets"] = []
            morphology["legacy_id"] = []

        return ListResponseReconstructionMorphologyRead(**response_data)

    @classmethod
    async def is_online(cls, *, httpx_client: AsyncClient, entitycore_url: str) -> bool:
        """Check if the tool is online."""
        response = await httpx_client.get(
            f"{entitycore_url.rstrip('/')}/health",
        )
        return response.status_code == 200
