"""Get All Measurement Annotations tool."""

from typing import ClassVar
from uuid import UUID

from httpx import AsyncClient
from pydantic import Field

from neuroagent.tools.autogenerated_types.entitycore import (
    ListResponseMeasurementAnnotationRead,
    ReadManyMeasurementAnnotationGetParametersQuery,
    WithinBrainRegionDirection,
)
from neuroagent.tools.base_tool import (
    BaseTool,
    EntitycoreExcludeBRParams,
    EntitycoreMetadata,
)


class MeasurementAnnotationGetAllInput(
    EntitycoreExcludeBRParams, ReadManyMeasurementAnnotationGetParametersQuery
):
    """Inputs for the measurement annotation get all tool."""

    within_brain_region_brain_region_id: UUID | None = Field(
        default=None,
        description="ID of the brain region of interest in UUID format.",
    )
    page_size: int = Field(
        ge=1,
        le=10,
        default=5,
        description="Number of items per page",
    )
    within_brain_region_direction: WithinBrainRegionDirection = Field(
        default="ascendants_and_descendants", title="Within Brain Region Direction"
    )


class MeasurementAnnotationGetAllTool(BaseTool):
    """Class defining the Get All Measurement Annotations logic."""

    name: ClassVar[str] = "entitycore-measurementannotation-getall"
    name_frontend: ClassVar[str] = "Get All Measurement Annotations"
    utterances: ClassVar[list[str]] = [
        "Find measurement annotations",
        "Show me available measurement annotations",
        "What measurement annotations are there?",
    ]
    description: ClassVar[
        str
    ] = """Searches the entitycore database to retrieve measurement annotations.
    The output is a list of measurement annotations, containing:
    - The measurement annotation ID
    - The creation date
    - The update date
    - The entity ID
    - The entity type
    - Any additional metadata

    We explicitly exclude the measurement kinds but you can access them using the Get One Measurement Annotation tool.
    """
    description_frontend: ClassVar[
        str
    ] = """Search and retrieve measurement annotations. Use this tool to:
    • Find annotations in specific brain regions
    • Filter by entity type
    • Access basic annotation data

    For detailed measurement kinds information, use the Get One Measurement Annotation tool.
    Specify brain region and optional criteria to find relevant annotations."""
    metadata: EntitycoreMetadata
    input_schema: MeasurementAnnotationGetAllInput

    async def arun(self) -> ListResponseMeasurementAnnotationRead:
        """From a brain region ID, extract measurement annotations.

        Returns
        -------
            list of MeasurementAnnotationRead to describe the annotations and their metadata, or an error dict.
        """
        query_params = self.input_schema.model_dump(exclude_defaults=True, mode="json")
        query_params["page_size"] = self.input_schema.page_size

        headers: dict[str, str] = {}
        if self.metadata.vlab_id is not None:
            headers["virtual-lab-id"] = str(self.metadata.vlab_id)
        if self.metadata.project_id is not None:
            headers["project-id"] = str(self.metadata.project_id)

        # Retrieve the hierarchy_id from br_id
        if self.input_schema.within_brain_region_brain_region_id is not None:
            brain_region = await self.metadata.httpx_client.get(
                url=self.metadata.entitycore_url.rstrip("/")
                + f"/brain-region/{self.input_schema.within_brain_region_brain_region_id}",
                headers=headers,
            )
            if brain_region.status_code != 200:
                raise ValueError(
                    f"The Brain Region endpoint returned a non 200 response code. Error: {brain_region.text}"
                )
            query_params["within_brain_region_hierarchy_id"] = brain_region.json()[
                "hierarchy_id"
            ]

        response = await self.metadata.httpx_client.get(
            url=self.metadata.entitycore_url.rstrip("/") + "/measurement-annotation",
            headers=headers,
            params=query_params,
        )
        if response.status_code != 200:
            raise ValueError(
                f"The measurement annotation endpoint returned a non 200 response code. Error: {response.text}"
            )

        response_data = response.json()
        # Set measurement_kinds to empty list for each annotation
        for annotation in response_data["data"]:
            annotation["measurement_kinds"] = []

        return ListResponseMeasurementAnnotationRead(**response_data)

    @classmethod
    async def is_online(cls, *, httpx_client: AsyncClient, entitycore_url: str) -> bool:
        """Check if the tool is online."""
        response = await httpx_client.get(
            f"{entitycore_url.rstrip('/')}/health",
        )
        return response.status_code == 200
