"""Get EModel tool."""

from typing import ClassVar

from httpx import AsyncClient
from pydantic import Field

from neuroagent.tools.autogenerated_types.entitycore import (
    ListResponseEModelReadExpanded,
    ReadManyEmodelGetParametersQuery,
)
from neuroagent.tools.base_tool import BaseMetadata, BaseTool


class EModelGetAllInput(ReadManyEmodelGetParametersQuery):
    """Inputs for the e-model get all tool."""

    page_size: int = Field(
        ge=1,
        le=10,
        default=5,
        description="Number of items per page",
    )


class EModelGetAllMetadata(BaseMetadata):
    """Metadata class for EModelGetAllTool."""

    httpx_client: AsyncClient
    entitycore_url: str
    vlab_id: str | None
    project_id: str | None


class EModelGetAllTool(BaseTool):
    """Class defining the Get EModel logic."""

    name: ClassVar[str] = "entitycore-emodel-getall"
    name_frontend: ClassVar[str] = "Get All E-Models"
    description: ClassVar[
        str
    ] = """Searches a neuroscience based knowledge graph to retrieve e-models.
    The output is a list of e-models, containing:
    - The e-model ID
    - The e-model name
    - The e-model description
    - The e-model iteration
    - The e-model score
    - The associated species
    - The associated brain region
    - The associated e-types and m-types
    - Creation and update dates

    We explicitly exclude the assets and ion channel models but you can access them using the Get One E-Model tool.
    """
    description_frontend: ClassVar[
        str
    ] = """Search and retrieve e-models. Use this tool to:
    • Find e-models by name
    • Filter by brain region
    • Filter by species
    • Access detailed e-model data

    Specify optional criteria to find relevant e-models."""
    metadata: EModelGetAllMetadata
    input_schema: EModelGetAllInput

    async def arun(self) -> ListResponseEModelReadExpanded:
        """Extract e-models.

        Returns
        -------
            list of e-models and their metadata, or an error dict.
        """
        query_params = self.input_schema.model_dump(exclude_defaults=True, mode="json")
        if "page_size" not in query_params:
            query_params["page_size"] = 5

        headers: dict[str, str] = {}
        if self.metadata.vlab_id is not None:
            headers["virtual-lab-id"] = self.metadata.vlab_id
        if self.metadata.project_id is not None:
            headers["project-id"] = self.metadata.project_id

        response = await self.metadata.httpx_client.get(
            url=self.metadata.entitycore_url.rstrip("/") + "/emodel",
            headers=headers,
            params=query_params,
        )
        if response.status_code != 200:
            raise ValueError(
                f"The emodel endpoint returned a non 200 response code. Error: {response.text}"
            )

        response_data = response.json()

        # Modify the data in place
        for emodel in response_data["data"]:
            emodel["assets"] = []
            emodel["ion_channel_models"] = []

        return ListResponseEModelReadExpanded(**response_data)

    @classmethod
    async def is_online(cls, *, httpx_client: AsyncClient, entitycore_url: str) -> bool:
        """Check if the tool is online."""
        response = await httpx_client.get(
            f"{entitycore_url.rstrip('/')}/health",
        )
        return response.status_code == 200
