"""Get All Electrical Cell Recordings tool."""

from typing import ClassVar
from uuid import UUID

from httpx import AsyncClient
from pydantic import Field
from pydantic.json_schema import SkipJsonSchema

from neuroagent.tools.autogenerated_types.entitycore import (
    ListResponseElectricalCellRecordingRead,
    ReadManyElectricalCellRecordingGetParametersQuery,
)
from neuroagent.tools.base_tool import BaseTool, EntitycoreMetadata


class ElectricalCellRecordingGetAllInput(
    ReadManyElectricalCellRecordingGetParametersQuery
):
    """Inputs for the electrical cell recording get all tool."""

    brain_region__id: SkipJsonSchema[None] = Field(default=None, exclude=True)
    brain_region__id__in: SkipJsonSchema[None] = Field(default=None, exclude=True)
    within_brain_region_hierarchy_id: UUID | None = Field(
        default=UUID("e3e70682-c209-4cac-a29f-6fbed82c07cd"),
        description="The hierarchy ID for brain regions. The default value is the most commonly used hierarchy ID.",
    )
    within_brain_region_brain_region_id: UUID | None = Field(
        default=None,
        description="ID of the brain region of interest in UUID format.",
    )
    page_size: int = Field(
        ge=1,
        le=10,
        default=5,
        description="Number of items per page",
    )


class ElectricalCellRecordingGetAllTool(BaseTool):
    """Class defining the Get All Electrical Cell Recordings logic."""

    name: ClassVar[str] = "entitycore-electricalcellrecording-getall"
    name_frontend: ClassVar[str] = "Get All Electrical Cell Recordings"
    description: ClassVar[
        str
    ] = """Searches the entitycore database to retrieve electrical cell recordings.
    The output is a list of electrical cell recordings, containing:
    - The brain region ID.
    - The brain region name.
    - The subject species name.
    - The recording ID.
    - The recording name.
    - The recording description.
    - The recording type.
    - The recording origin.
    - The recording location.
    - The liquid junction potential.
    - Any additional metadata.

    We explicitly exclude the assets and the legacy id but you can access them using the Get One Electrical Cell Recording tool.
    """
    description_frontend: ClassVar[
        str
    ] = """Search and retrieve electrical cell recordings. Use this tool to:
    • Find recordings in specific brain regions
    • Filter by recording type and origin
    • Access detailed recording data

    Specify brain region and optional criteria to find relevant recordings."""
    metadata: EntitycoreMetadata
    input_schema: ElectricalCellRecordingGetAllInput

    async def arun(self) -> ListResponseElectricalCellRecordingRead:
        """From a brain region ID, extract electrical cell recordings.

        Returns
        -------
            list of ElectricalCellRecordingRead to describe the recordings and their metadata, or an error dict.
        """
        query_params = self.input_schema.model_dump(exclude_defaults=True, mode="json")
        query_params["page_size"] = self.input_schema.page_size
        query_params["within_brain_region_hierarchy_id"] = (
            self.input_schema.within_brain_region_hierarchy_id
        )

        headers: dict[str, str] = {}
        if self.metadata.vlab_id is not None:
            headers["virtual-lab-id"] = self.metadata.vlab_id
        if self.metadata.project_id is not None:
            headers["project-id"] = self.metadata.project_id

        response = await self.metadata.httpx_client.get(
            url=self.metadata.entitycore_url.rstrip("/") + "/electrical-cell-recording",
            headers=headers,
            params=query_params,
        )
        if response.status_code != 200:
            raise ValueError(
                f"The electrical cell recording endpoint returned a non 200 response code. Error: {response.text}"
            )

        response_data = response.json()
        # Set assets and legacy_id to empty lists for each recording
        for recording in response_data["data"]:
            recording["assets"] = []
            recording["legacy_id"] = []

        return ListResponseElectricalCellRecordingRead(**response_data)

    @classmethod
    async def is_online(cls, *, httpx_client: AsyncClient, entitycore_url: str) -> bool:
        """Check if the tool is online."""
        response = await httpx_client.get(
            f"{entitycore_url.rstrip('/')}/health",
        )
        return response.status_code == 200
