"""Get All SimulationGeneration tool."""

from typing import ClassVar

from httpx import AsyncClient
from pydantic import Field

from neuroagent.tools.autogenerated_types.entitycore import (
    ListResponseSimulationGenerationRead,
    ReadManySimulationGenerationGetParametersQuery,
)
from neuroagent.tools.base_tool import BaseTool, EntitycoreMetadata


class SimulationGenerationGetAllInput(ReadManySimulationGenerationGetParametersQuery):
    """Inputs for the simulation-generation get all tool."""

    page_size: int = Field(
        ge=1,
        le=10,
        default=5,
        description="Number of items per page",
    )


class SimulationGenerationGetAllTool(BaseTool):
    """Class defining the Get All Simulation Generations logic."""

    name: ClassVar[str] = "entitycore-simulationgeneration-getall"
    name_frontend: ClassVar[str] = "Get All Simulation Generations"
    description: ClassVar[
        str
    ] = """Searches a neuroscience based knowledge graph to retrieve simulation-generations.
    The output is a list of simulation-generations, containing:
    - The simulation generation ID and basic identifiers
    - Core simulation generation information and properties
    - Simulation parameters and configuration
    - Creation and modification timestamps
    """
    description_frontend: ClassVar[
        str
    ] = """Search and retrieve simulation-generations. Use this tool to:
    • Find simulation-generations by various criteria
    • Access detailed simulation-generation data

    Specify optional criteria to find relevant simulation-generations."""
    metadata: EntitycoreMetadata
    input_schema: SimulationGenerationGetAllInput

    async def arun(self) -> ListResponseSimulationGenerationRead:
        """Extract simulation-generations.

        Returns
        -------
            list of simulation-generations and their metadata, or an error dict.
        """
        query_params = self.input_schema.model_dump(exclude_defaults=True, mode="json")
        query_params["page_size"] = self.input_schema.page_size

        headers: dict[str, str] = {}
        if self.metadata.vlab_id is not None:
            headers["virtual-lab-id"] = self.metadata.vlab_id
        if self.metadata.project_id is not None:
            headers["project-id"] = self.metadata.project_id

        response = await self.metadata.httpx_client.get(
            url=self.metadata.entitycore_url.rstrip("/") + "/simulation-generation",
            headers=headers,
            params=query_params,
        )
        if response.status_code != 200:
            raise ValueError(
                f"The simulation-generation endpoint returned a non 200 response code. Error: {response.text}"
            )

        response_data = response.json()
        return ListResponseSimulationGenerationRead(**response_data)

    @classmethod
    async def is_online(cls, *, httpx_client: AsyncClient, entitycore_url: str) -> bool:
        """Check if the tool is online."""
        response = await httpx_client.get(
            f"{entitycore_url.rstrip('/')}/health",
        )
        return response.status_code == 200
