"""Get One Contribution tool."""

from typing import ClassVar
from uuid import UUID

from httpx import AsyncClient
from pydantic import BaseModel, Field

from neuroagent.tools.autogenerated_types.entitycore import (
    ContributionReadWithoutEntity,
)
from neuroagent.tools.base_tool import BaseMetadata, BaseTool


class ContributionGetOneInput(BaseModel):
    """Inputs of the knowledge graph API."""

    contribution_id: UUID = Field(
        description="ID of the contribution of interest in UUID format."
    )


class ContributionGetOneMetadata(BaseMetadata):
    """Metadata class for ContributionGetOneTool."""

    httpx_client: AsyncClient
    entitycore_url: str
    vlab_id: str | None
    project_id: str | None


class ContributionGetOneTool(BaseTool):
    """Class defining the Get One Contribution logic."""

    name: ClassVar[str] = "entitycore-contribution-getone"
    name_frontend: ClassVar[str] = "Get One Contribution"
    description: ClassVar[
        str
    ] = """Retrieves detailed information about a specific contribution from the knowledge graph.
    Requires a 'contribution_id' which is the ID of the contribution of interest as registered in the knowledge graph.
    The output contains detailed information about the contribution, including:
    - The contribution ID
    - The agent (person or organization) making the contribution
    - The role of the agent
    - Creation and update dates
    """
    description_frontend: ClassVar[
        str
    ] = """Get detailed information about a specific contribution. Use this tool to:
    • View complete contribution details
    • Access agent and role information
    • Get creation and update information

    Specify the contribution ID to retrieve its full details."""
    metadata: ContributionGetOneMetadata
    input_schema: ContributionGetOneInput

    async def arun(self) -> ContributionReadWithoutEntity:
        """From a contribution ID, extract detailed contribution information.

        Returns
        -------
            ContributionReadWithoutEntity containing detailed contribution information, or an error dict.
        """
        headers: dict[str, str] = {}
        if self.metadata.vlab_id is not None:
            headers["virtual-lab-id"] = self.metadata.vlab_id
        if self.metadata.project_id is not None:
            headers["project-id"] = self.metadata.project_id

        response = await self.metadata.httpx_client.get(
            url=self.metadata.entitycore_url.rstrip("/")
            + f"/contribution/{self.input_schema.contribution_id}",
            headers=headers,
        )
        if response.status_code != 200:
            raise ValueError(
                f"The contribution endpoint returned a non 200 response code. Error: {response.text}"
            )
        return ContributionReadWithoutEntity(**response.json())

    @classmethod
    async def is_online(cls, *, httpx_client: AsyncClient, entitycore_url: str) -> bool:
        """Check if the tool is online."""
        response = await httpx_client.get(
            f"{entitycore_url.rstrip('/')}/health",
        )
        return response.status_code == 200
