"""Get One Experimental Neuron Density tool."""

from typing import ClassVar
from uuid import UUID

from httpx import AsyncClient
from pydantic import BaseModel, Field

from neuroagent.tools.autogenerated_types.entitycore import (
    ExperimentalNeuronDensityRead,
)
from neuroagent.tools.base_tool import BaseTool, EntitycoreMetadata


class ExperimentalNeuronDensityGetOneInput(BaseModel):
    """Inputs of the knowledge graph API."""

    density_id: UUID = Field(
        description="ID of the experimental neuron density of interest in UUID format."
    )


class ExperimentalNeuronDensityGetOneOutput(ExperimentalNeuronDensityRead):
    """Entitycore class modification, with added links."""

    url_link: str


class ExperimentalNeuronDensityGetOneTool(BaseTool):
    """Class defining the Get One Experimental Neuron Density logic."""

    name: ClassVar[str] = "entitycore-experimentalneurondensity-getone"
    name_frontend: ClassVar[str] = "Get One Experimental Neuron Density"
    description: ClassVar[
        str
    ] = """Retrieves detailed information about a specific experimental neuron density from the knowledge graph.
    Requires a 'density_id' which is the ID of the density of interest as registered in the knowledge graph.
    The output contains detailed information about the density, including:
    - The density ID (it is the `id` field in the response - ignore other IDs)
    - The density name
    - The density description
    - Associated brain region information
    - Subject species information
    - Associated measurements
    - Associated assets
    - Associated contributions
    - Associated mtypes and etypes
    """
    description_frontend: ClassVar[
        str
    ] = """Get detailed information about a specific experimental neuron density. Use this tool to:
    • View complete density details
    • Access associated metadata
    • Get brain region and species information

    Specify the density ID to retrieve its full details."""
    metadata: EntitycoreMetadata
    input_schema: ExperimentalNeuronDensityGetOneInput

    async def arun(self) -> ExperimentalNeuronDensityGetOneOutput:
        """From a density ID, extract detailed density information.

        Returns
        -------
            ExperimentalNeuronDensityRead containing detailed density information, or an error dict.
        """
        headers: dict[str, str] = {}
        if self.metadata.vlab_id is not None:
            headers["virtual-lab-id"] = str(self.metadata.vlab_id)
        if self.metadata.project_id is not None:
            headers["project-id"] = str(self.metadata.project_id)

        response = await self.metadata.httpx_client.get(
            url=self.metadata.entitycore_url.rstrip("/")
            + f"/experimental-neuron-density/{self.input_schema.density_id}",
            headers=headers,
        )
        if response.status_code != 200:
            raise ValueError(
                f"The experimental neuron density endpoint returned a non 200 response code. Error: {response.text}"
            )
        # Add the link
        response_json = response.json()
        response_json["url_link"] = (
            self.metadata.entity_frontend_url
            + "/explore/interactive/experimental"
            + "/neuron-density/"
            + response_json["id"]
        )
        return ExperimentalNeuronDensityGetOneOutput(**response_json)

    @classmethod
    async def is_online(cls, *, httpx_client: AsyncClient, entitycore_url: str) -> bool:
        """Check if the tool is online."""
        response = await httpx_client.get(
            f"{entitycore_url.rstrip('/')}/health",
        )
        return response.status_code == 200
