"""Get One Circuit tool."""

from typing import ClassVar
from uuid import UUID

from httpx import AsyncClient
from pydantic import BaseModel, Field

from neuroagent.tools.autogenerated_types.entitycore import (
    CircuitRead,
)
from neuroagent.tools.base_tool import BaseTool, EntitycoreMetadata


class CircuitGetOneInput(BaseModel):
    """Inputs for the circuit get one tool."""

    circuit_id: UUID = Field(
        description="ID of the circuit of interest in UUID format."
    )


class CircuitGetOneTool(BaseTool):
    """Class defining the Get One Circuit logic."""

    name: ClassVar[str] = "entitycore-circuit-getone"
    name_frontend: ClassVar[str] = "Get One Circuit"
    utterances: ClassVar[list[str]] = [
        "Get details for this circuit",
        "Show me information about this circuit",
        "What are the properties of this circuit?",
    ]
    description: ClassVar[
        str
    ] = """Retrieves detailed information about a specific circuit from the knowledge graph.
    Requires a 'circuit_id' which is the ID of the circuit of interest as registered in the knowledge graph.
    The output contains detailed information about the circuit, including:
    - The circuit ID and basic identifiers
    - Core circuit information and properties
    - Status and state information
    - Associated metadata and relationships
    - Creation and modification timestamps
    - Creation and update dates
    """
    description_frontend: ClassVar[
        str
    ] = """Get detailed information about a specific circuit. Use this tool to:
    • View complete circuit details
    • Access detailed circuit information
    • Get creation and update information

    Specify the circuit ID to retrieve its full details."""
    metadata: EntitycoreMetadata
    input_schema: CircuitGetOneInput

    async def arun(self) -> CircuitRead:
        """From a circuit ID, extract detailed circuit information.

        Returns
        -------
            CircuitRead containing detailed circuit information, or an error dict.
        """
        headers: dict[str, str] = {}
        if self.metadata.vlab_id is not None:
            headers["virtual-lab-id"] = str(self.metadata.vlab_id)
        if self.metadata.project_id is not None:
            headers["project-id"] = str(self.metadata.project_id)

        response = await self.metadata.httpx_client.get(
            url=self.metadata.entitycore_url.rstrip("/")
            + f"/circuit/{self.input_schema.circuit_id}",
            headers=headers,
        )
        if response.status_code != 200:
            raise ValueError(
                f"The circuit endpoint returned a non 200 response code. Error: {response.text}"
            )

        response_data = response.json()
        response_data["url_link"] = (
            self.metadata.entity_frontend_url + "/" + response_data["id"]
        )
        return CircuitRead(**response_data)

    @classmethod
    async def is_online(cls, *, httpx_client: AsyncClient, entitycore_url: str) -> bool:
        """Check if the tool is online."""
        response = await httpx_client.get(
            f"{entitycore_url.rstrip('/')}/health",
        )
        return response.status_code == 200
