"""Get All Assets tool."""

from typing import ClassVar
from uuid import UUID

from httpx import AsyncClient
from pydantic import BaseModel, Field

from neuroagent.schemas import EntityRoute
from neuroagent.tools.autogenerated_types.entitycore import ListResponseAssetRead
from neuroagent.tools.base_tool import BaseTool, EntitycoreMetadata


class AssetGetAllInputSchema(BaseModel):
    """Input schema for AssetGetAllTool."""

    entity_route: EntityRoute = Field(description="The route of the entity")
    entity_id: UUID = Field(description="The ID of the entity")


class AssetGetAllTool(BaseTool):
    """Class defining the Get All Assets logic."""

    name: ClassVar[str] = "entitycore-asset-getall"
    name_frontend: ClassVar[str] = "Get All Assets"
    description: ClassVar[str] = """Retrieves all assets from the entitycore service.
    The output contains a list of assets, each containing:
    - The asset path
    - The asset full path
    - Whether it's a directory
    - Content type
    - Size
    - SHA256 digest
    - Metadata
    - Label
    - ID
    - Status
    """
    description_frontend: ClassVar[str] = """Retrieve all assets. Use this tool to:
    • Get a list of all assets for an entity
    • Filter assets by ID
    • Access asset metadata and properties

    Specify the entity route and entity ID to retrieve the assets."""
    metadata: EntitycoreMetadata
    input_schema: AssetGetAllInputSchema

    async def arun(self) -> ListResponseAssetRead:
        """Get all assets.

        Returns
        -------
            List of assets and their metadata, or an error dict.
        """
        headers: dict[str, str] = {}
        if self.metadata.vlab_id is not None:
            headers["virtual-lab-id"] = str(self.metadata.vlab_id)
        if self.metadata.project_id is not None:
            headers["project-id"] = str(self.metadata.project_id)

        response = await self.metadata.httpx_client.get(
            url=f"{self.metadata.entitycore_url.rstrip('/')}/{self.input_schema.entity_route}/{self.input_schema.entity_id}/assets",
            headers=headers,
        )
        if response.status_code != 200:
            raise ValueError(
                f"The asset endpoint returned a non 200 response code. Error: {response.text}"
            )

        response_data = response.json()
        return ListResponseAssetRead(**response_data)

    @classmethod
    async def is_online(cls, *, httpx_client: AsyncClient, entitycore_url: str) -> bool:
        """Check if the tool is online."""
        response = await httpx_client.get(
            f"{entitycore_url.rstrip('/')}/health",
        )
        return response.status_code == 200
