"""Get All Ion Channels tool."""

from typing import ClassVar

from httpx import AsyncClient
from pydantic import Field

from neuroagent.autogenerated_types.entitycore import (
    ListResponseIonChannelRead,
    ReadManyIonChannelGetParametersQuery,
)
from neuroagent.tools.base_tool import BaseTool, EntitycoreMetadata


class IonChannelGetAllInput(ReadManyIonChannelGetParametersQuery):
    """Inputs for the ion-channel get all tool."""

    page_size: int = Field(
        ge=1,
        le=10,
        default=5,
        description="Number of items per page",
    )


class IonChannelGetAllTool(BaseTool):
    """Class defining the Get All Ion Channels logic."""

    name: ClassVar[str] = "entitycore-ionchannel-getall"
    name_frontend: ClassVar[str] = "Get All Ion Channels"
    description: ClassVar[
        str
    ] = """Searches a neuroscience based knowledge graph to retrieve ion-channels.
    The output is a list of ion-channels, containing:
    - The ion channel ID and basic identifiers
    - Core ion channel information and properties
    - Status and state information
    - Associated metadata and relationships
    - Creation and modification timestamps
    """
    description_frontend: ClassVar[
        str
    ] = """Search and retrieve ion-channels. Use this tool to:
    • Find ion-channels by various criteria
    • Access detailed ion-channel data

    Specify optional criteria to find relevant ion-channels."""
    metadata: EntitycoreMetadata
    input_schema: IonChannelGetAllInput

    async def arun(self) -> ListResponseIonChannelRead:
        """Extract ion-channels.

        Returns
        -------
            list of ion-channels and their metadata, or an error dict.
        """
        query_params = self.input_schema.model_dump(exclude_defaults=True, mode="json")
        query_params["page_size"] = self.input_schema.page_size

        headers: dict[str, str] = {}
        if self.metadata.vlab_id is not None:
            headers["virtual-lab-id"] = str(self.metadata.vlab_id)
        if self.metadata.project_id is not None:
            headers["project-id"] = str(self.metadata.project_id)

        response = await self.metadata.httpx_client.get(
            url=self.metadata.entitycore_url.rstrip("/") + "/ion-channel",
            headers=headers,
            params=query_params,
        )
        if response.status_code != 200:
            raise ValueError(
                f"The ion-channel endpoint returned a non 200 response code. Error: {response.text}"
            )

        response_data = response.json()
        return ListResponseIonChannelRead(**response_data)

    @classmethod
    async def is_online(cls, *, httpx_client: AsyncClient, entitycore_url: str) -> bool:
        """Check if the tool is online."""
        response = await httpx_client.get(
            f"{entitycore_url.rstrip('/')}/health",
        )
        return response.status_code == 200
