"""Get All SingleNeuronSynaptomeSimulation tool."""

from typing import ClassVar
from uuid import UUID

from httpx import AsyncClient
from pydantic import Field

from neuroagent.tools.autogenerated_types.entitycore import (
    ListResponseSingleNeuronSynaptomeSimulationRead,
    ReadManySingleNeuronSynaptomeSimulationGetParametersQuery,
)
from neuroagent.tools.base_tool import BaseTool, EntitycoreMetadata


class SingleNeuronSynaptomeSimulationGetAllInput(
    ReadManySingleNeuronSynaptomeSimulationGetParametersQuery
):
    """Inputs for the single-neuron-synaptome-simulation get all tool."""

    within_brain_region_brain_region_id: UUID | None = Field(
        default=None,
        description=(
            """UUID of a brain region. Returns items in that region and **all its sub-regions**. "
            Make an educated guess on whether the user wants to include sub-regions or not
            and use this when you want a broad match including sub-regions.
            To look up the UUID, first call the resolve-brain-region-tool."""
        ),
    )
    within_brain_region_hierarchy_id: UUID | None = Field(
        default=UUID("e3e70682-c209-4cac-a29f-6fbed82c07cd"),
        description="The hierarchy ID for brain regions. The default value is the most commonly used hierarchy ID.",
    )
    brain_region__id: UUID | None = Field(
        default=None,
        description=(
            """UUID of a brain region. Returns items **only** in that exact region (no sub-regions). "
            Make an educated guess on whether the user wants to include sub-regions or not
            and use this when you need a narrow, exact match.
            To look up the UUID, first call the resolve-brain-region-tool."""
        ),
    )
    page_size: int = Field(
        ge=1,
        le=10,
        default=5,
        description="Number of items per page",
    )


class SingleNeuronSynaptomeSimulationGetAllTool(BaseTool):
    """Class defining the Get All Single Neuron Synaptome Simulations logic."""

    name: ClassVar[str] = "entitycore-singleneuronsynaptomesimulation-getall"
    name_frontend: ClassVar[str] = "Get All Single Neuron Synaptome Simulations"
    description: ClassVar[
        str
    ] = """Searches a neuroscience based knowledge graph to retrieve single-neuron-synaptome-simulations.
    The output is a list of single-neuron-synaptome-simulations, containing:
    - The single neuron synaptome simulation ID and basic identifiers
    - Core single neuron synaptome simulation information and properties
    - Simulation parameters and configuration
    - Creation and modification timestamps
    """
    description_frontend: ClassVar[
        str
    ] = """Search and retrieve single-neuron-synaptome-simulations. Use this tool to:
    • Find single-neuron-synaptome-simulations by various criteria
    • Access detailed single-neuron-synaptome-simulation data

    Specify optional criteria to find relevant single-neuron-synaptome-simulations."""
    metadata: EntitycoreMetadata
    input_schema: SingleNeuronSynaptomeSimulationGetAllInput

    async def arun(self) -> ListResponseSingleNeuronSynaptomeSimulationRead:
        """Extract single-neuron-synaptome-simulations.

        Returns
        -------
            list of single-neuron-synaptome-simulations and their metadata, or an error dict.
        """
        query_params = self.input_schema.model_dump(exclude_defaults=True, mode="json")
        query_params["page_size"] = self.input_schema.page_size

        headers: dict[str, str] = {}
        if self.metadata.vlab_id is not None:
            headers["virtual-lab-id"] = self.metadata.vlab_id
        if self.metadata.project_id is not None:
            headers["project-id"] = self.metadata.project_id

        response = await self.metadata.httpx_client.get(
            url=self.metadata.entitycore_url.rstrip("/")
            + "/single-neuron-synaptome-simulation",
            headers=headers,
            params=query_params,
        )
        if response.status_code != 200:
            raise ValueError(
                f"The single-neuron-synaptome-simulation endpoint returned a non 200 response code. Error: {response.text}"
            )

        response_data = response.json()
        return ListResponseSingleNeuronSynaptomeSimulationRead(**response_data)

    @classmethod
    async def is_online(cls, *, httpx_client: AsyncClient, entitycore_url: str) -> bool:
        """Check if the tool is online."""
        response = await httpx_client.get(
            f"{entitycore_url.rstrip('/')}/health",
        )
        return response.status_code == 200
