"""Get One SimulationResult tool."""

from typing import ClassVar
from uuid import UUID

from httpx import AsyncClient
from pydantic import BaseModel, Field

from neuroagent.tools.autogenerated_types.entitycore import (
    SimulationResultRead,
)
from neuroagent.tools.base_tool import BaseTool, EntitycoreMetadata


class SimulationResultGetOneInput(BaseModel):
    """Inputs for the simulation-result get one tool."""

    simulation_result_id: UUID = Field(
        description="ID of the simulation-result of interest in UUID format."
    )


class SimulationResultGetOneTool(BaseTool):
    """Class defining the Get One SimulationResult logic."""

    name: ClassVar[str] = "entitycore-simulationresult-getone"
    name_frontend: ClassVar[str] = "Get One Simulation Result"
    description: ClassVar[
        str
    ] = """Retrieves detailed information about a specific simulation-result from the knowledge graph.
    Requires a 'simulation_result_id' which is the ID of the simulation-result of interest as registered in the knowledge graph.
    The output contains detailed information about the simulation-result, including:
    - The simulation result ID and basic identifiers
    - Core simulation result information and properties
    - Simulation parameters and configuration
    - Creation and modification timestamps
    - Creation and update dates
    """
    description_frontend: ClassVar[
        str
    ] = """Get detailed information about a specific simulation-result. Use this tool to:
    • View complete simulation-result details
    • Access detailed simulation-result information
    • Get creation and update information

    Specify the simulation-result ID to retrieve its full details."""
    metadata: EntitycoreMetadata
    input_schema: SimulationResultGetOneInput

    async def arun(self) -> SimulationResultRead:
        """From a simulation-result ID, extract detailed simulation-result information.

        Returns
        -------
            SimulationResultRead containing detailed simulation-result information, or an error dict.
        """
        headers: dict[str, str] = {}
        if self.metadata.vlab_id is not None:
            headers["virtual-lab-id"] = str(self.metadata.vlab_id)
        if self.metadata.project_id is not None:
            headers["project-id"] = str(self.metadata.project_id)

        response = await self.metadata.httpx_client.get(
            url=self.metadata.entitycore_url.rstrip("/")
            + f"/simulation-result/{self.input_schema.simulation_result_id}",
            headers=headers,
        )
        if response.status_code != 200:
            raise ValueError(
                f"The simulation-result endpoint returned a non 200 response code. Error: {response.text}"
            )
        return SimulationResultRead(**response.json())

    @classmethod
    async def is_online(cls, *, httpx_client: AsyncClient, entitycore_url: str) -> bool:
        """Check if the tool is online."""
        response = await httpx_client.get(
            f"{entitycore_url.rstrip('/')}/health",
        )
        return response.status_code == 200
