"""Get All Electrical Cell Recordings tool."""

from typing import ClassVar, Literal

from httpx import AsyncClient
from pydantic import Field

from neuroagent.tools.autogenerated_types.entitycore import (
    ListResponseElectricalCellRecordingRead,
    ReadManyElectricalCellRecordingGetParametersQuery,
)
from neuroagent.tools.base_tool import BaseMetadata, BaseTool


class ElectricalCellRecordingGetAllInput(
    ReadManyElectricalCellRecordingGetParametersQuery
):
    """Inputs for the electrical cell recording get all tool."""

    within_brain_region_brain_region_id: str | None = Field(  # type: ignore[assignment]
        default=None,
        description="ID of the brain region of interest in UUID format. To find the ID use the resolve-brain-region-tool first.",
    )
    within_brain_region_hierarchy_id: Literal[
        "e3e70682-c209-4cac-a29f-6fbed82c07cd"
    ] = Field(  # type: ignore[assignment]
        default="e3e70682-c209-4cac-a29f-6fbed82c07cd",
        description="The hierarchy ID for brain regions. This is fixed to ensure consistent results.",
    )


class ElectricalCellRecordingGetAllMetadata(BaseMetadata):
    """Metadata class for ElectricalCellRecordingGetAllTool."""

    httpx_client: AsyncClient
    entitycore_url: str
    vlab_id: str | None
    project_id: str | None


class ElectricalCellRecordingGetAllTool(BaseTool):
    """Class defining the Get All Electrical Cell Recordings logic."""

    name: ClassVar[str] = "entitycore-electricalcellrecording-getall"
    name_frontend: ClassVar[str] = "Get All Electrical Cell Recordings"
    description: ClassVar[
        str
    ] = """Searches the entitycore database to retrieve electrical cell recordings.
    Optionally accepts a brain_region__id to filter recordings by brain region.
    The output is a list of electrical cell recordings, containing:
    - The brain region ID.
    - The brain region name.
    - The subject species name.
    - The recording ID.
    - The recording name.
    - The recording description.
    - The recording type.
    - The recording origin.
    - The recording location.
    - The liquid junction potential.
    - Any additional metadata.

    We explicitly exclude the assets and the legacy id but you can access them using the Get One Electrical Cell Recording tool.
    """
    description_frontend: ClassVar[
        str
    ] = """Search and retrieve electrical cell recordings. Use this tool to:
    • Find recordings in specific brain regions
    • Filter by recording type and origin
    • Access detailed recording data

    Specify brain region and optional criteria to find relevant recordings."""
    metadata: ElectricalCellRecordingGetAllMetadata
    input_schema: ElectricalCellRecordingGetAllInput

    async def arun(self) -> ListResponseElectricalCellRecordingRead:
        """From a brain region ID, extract electrical cell recordings.

        Returns
        -------
            list of ElectricalCellRecordingRead to describe the recordings and their metadata, or an error dict.
        """
        query_params = self.input_schema.model_dump(exclude_defaults=True, mode="json")

        headers: dict[str, str] = {}
        if self.metadata.vlab_id is not None:
            headers["virtual-lab-id"] = self.metadata.vlab_id
        if self.metadata.project_id is not None:
            headers["project-id"] = self.metadata.project_id

        response = await self.metadata.httpx_client.get(
            url=self.metadata.entitycore_url.rstrip("/") + "/electrical-cell-recording",
            headers=headers,
            params=query_params,
        )
        if response.status_code != 200:
            raise ValueError(
                f"The electrical cell recording endpoint returned a non 200 response code. Error: {response.text}"
            )

        response_data = response.json()
        # Set assets and legacy_id to empty lists for each recording
        for recording in response_data["data"]:
            recording["assets"] = []
            recording["legacy_id"] = []

        return ListResponseElectricalCellRecordingRead(**response_data)

    @classmethod
    async def is_online(cls, *, httpx_client: AsyncClient, entitycore_url: str) -> bool:
        """Check if the tool is online."""
        response = await httpx_client.get(
            f"{entitycore_url.rstrip('/')}/health",
        )
        return response.status_code == 200
