"""Get Mtype tool."""

from typing import ClassVar

from httpx import AsyncClient
from pydantic import Field

from neuroagent.tools.autogenerated_types.entitycore import (
    ListResponseAnnotation,
    ReadManyMtypeGetParametersQuery,
)
from neuroagent.tools.base_tool import BaseMetadata, BaseTool


class MtypeGetAllInput(ReadManyMtypeGetParametersQuery):
    """Inputs for the m-type get all tool."""

    page_size: int = Field(
        ge=1,
        le=10,
        default=5,
        description="Number of items per page",
    )


class MtypeGetAllMetadata(BaseMetadata):
    """Metadata class for MtypeGetAllTool."""

    httpx_client: AsyncClient
    entitycore_url: str
    vlab_id: str | None
    project_id: str | None


class MtypeGetAllTool(BaseTool):
    """Class defining the Get Mtype logic."""

    name: ClassVar[str] = "entitycore-mtype-getall"
    name_frontend: ClassVar[str] = "Get All M-types"
    description: ClassVar[
        str
    ] = """Searches a neuroscience based knowledge graph to retrieve m-types.
    The output is a list of m-types, containing:
    - The m-type ID
    - The m-type preferred label
    - The m-type description
    """
    description_frontend: ClassVar[
        str
    ] = """Search and retrieve m-types. Use this tool to:
    • Find m-types by preferred label
    • Access detailed m-type data

    Specify optional criteria to find relevant m-types."""
    metadata: MtypeGetAllMetadata
    input_schema: MtypeGetAllInput

    async def arun(self) -> ListResponseAnnotation:
        """Extract m-types.

        Returns
        -------
            list of m-types and their metadata, or an error dict.
        """
        query_params = self.input_schema.model_dump(exclude_defaults=True, mode="json")
        if "page_size" not in query_params:
            query_params["page_size"] = 5

        headers: dict[str, str] = {}
        if self.metadata.vlab_id is not None:
            headers["virtual-lab-id"] = self.metadata.vlab_id
        if self.metadata.project_id is not None:
            headers["project-id"] = self.metadata.project_id

        response = await self.metadata.httpx_client.get(
            url=self.metadata.entitycore_url.rstrip("/") + "/mtype",
            headers=headers,
            params=query_params,
        )
        if response.status_code != 200:
            raise ValueError(
                f"The mtype endpoint returned a non 200 response code. Error: {response.text}"
            )

        response_data = response.json()
        return ListResponseAnnotation(**response_data)

    @classmethod
    async def is_online(cls, *, httpx_client: AsyncClient, entitycore_url: str) -> bool:
        """Check if the tool is online."""
        response = await httpx_client.get(
            f"{entitycore_url.rstrip('/')}/health",
        )
        return response.status_code == 200
