"""Get All Circuits tool."""

from typing import ClassVar
from uuid import UUID

from httpx import AsyncClient
from pydantic import Field
from pydantic.json_schema import SkipJsonSchema

from neuroagent.tools.autogenerated_types.entitycore import (
    ListResponseCircuitRead,
    ReadManyCircuitGetParametersQuery,
)
from neuroagent.tools.base_tool import BaseTool, EntitycoreMetadata


class CircuitGetAllInput(ReadManyCircuitGetParametersQuery):
    """Inputs for the circuit get all tool."""

    brain_region__id: SkipJsonSchema[None] = Field(default=None, exclude=True)
    brain_region__id__in: SkipJsonSchema[None] = Field(default=None, exclude=True)
    within_brain_region_hierarchy_id: UUID | None = Field(
        default=UUID("e3e70682-c209-4cac-a29f-6fbed82c07cd"),
        description="The hierarchy ID for brain regions. The default value is the most commonly used hierarchy ID.",
    )
    within_brain_region_brain_region_id: UUID | None = Field(
        default=None,
        description="ID of the brain region of interest in UUID format.",
    )
    page_size: int = Field(
        ge=1,
        le=10,
        default=5,
        description="Number of items per page",
    )


class CircuitGetAllTool(BaseTool):
    """Class defining the Get All Circuits logic."""

    name: ClassVar[str] = "entitycore-circuit-getall"
    name_frontend: ClassVar[str] = "Get All Circuits"
    description: ClassVar[
        str
    ] = """Searches a neuroscience based knowledge graph to retrieve circuits.
    The output is a list of circuits, containing:
    - The circuit ID and basic identifiers
    - Core circuit information and properties
    - Status and state information
    - Associated metadata and relationships
    - Creation and modification timestamps
    """
    description_frontend: ClassVar[
        str
    ] = """Search and retrieve circuits. Use this tool to:
    • Find circuits by various criteria
    • Access detailed circuit data

    Specify optional criteria to find relevant circuits."""
    metadata: EntitycoreMetadata
    input_schema: CircuitGetAllInput

    async def arun(self) -> ListResponseCircuitRead:
        """Extract circuits.

        Returns
        -------
            list of circuits and their metadata, or an error dict.
        """
        query_params = self.input_schema.model_dump(exclude_defaults=True, mode="json")
        query_params["page_size"] = self.input_schema.page_size
        query_params["within_brain_region_hierarchy_id"] = (
            self.input_schema.within_brain_region_hierarchy_id
        )

        headers: dict[str, str] = {}
        if self.metadata.vlab_id is not None:
            headers["virtual-lab-id"] = self.metadata.vlab_id
        if self.metadata.project_id is not None:
            headers["project-id"] = self.metadata.project_id

        response = await self.metadata.httpx_client.get(
            url=self.metadata.entitycore_url.rstrip("/") + "/circuit",
            headers=headers,
            params=query_params,
        )
        if response.status_code != 200:
            raise ValueError(
                f"The circuit endpoint returned a non 200 response code. Error: {response.text}"
            )

        response_data = response.json()
        for circuit in response_data["data"]:
            circuit["assets"] = []

        return ListResponseCircuitRead(**response_data)

    @classmethod
    async def is_online(cls, *, httpx_client: AsyncClient, entitycore_url: str) -> bool:
        """Check if the tool is online."""
        response = await httpx_client.get(
            f"{entitycore_url.rstrip('/')}/health",
        )
        return response.status_code == 200
