"""Tool to generate an obi-one compatible simulation config."""

import json
from typing import Any, ClassVar
from uuid import UUID

from httpx import AsyncClient
from openai import AsyncOpenAI
from pydantic import BaseModel, Field
from pydantic.json_schema import SkipJsonSchema

from neuroagent.new_types import SharedState
from neuroagent.tools.autogenerated_types.obione import (
    CircuitFromID,
    CircuitSimulationScanConfig,
    Initialize1,
)
from neuroagent.tools.base_tool import BaseMetadata, BaseTool
from neuroagent.utils import get_token_count


def extract_model_structure(model: type[BaseModel]) -> dict[str, Any]:
    """Recursively extract nested field structure from a Pydantic model."""
    result = {}
    for name, field_info in model.model_fields.items():
        field_type = field_info.annotation

        if isinstance(field_type, type) and issubclass(field_type, BaseModel):
            result[name] = extract_model_structure(field_type)
        else:
            result[name] = {}

    return result


class GenerateSimulationsConfigInput(BaseModel):
    """Inputs of the GenerateSimulationsConfig tool."""

    circuit_id: UUID = Field(
        description="UUID of the target circuit that has to be simulated."
    )
    config_request: str = Field(
        description="A detailed description of the desired simulation configuration that will be processed by an LLM to generate JSON. This should contain either: (1) a complete specification for a new configuration including all required parameters and settings, or (2) specific modifications to be applied to an existing configuration (e.g., 'change simulation length to 5000ms', 'Apply an extra stimulus for excitatory neurons', 'record only inhibitory neurons instead'). Be explicit about which approach you're using and provide clear, actionable details."
    )


class GenerateSimulationsConfigMetadata(BaseMetadata):
    """Metadata of the GenerateSimulationsConfig tool."""

    openai_client: AsyncOpenAI
    httpx_client: AsyncClient
    obi_one_url: str
    vlab_id: UUID | None
    project_id: UUID | None
    shared_state: SharedState | None
    entity_frontend_url: str
    token_consumption: dict[str, str | int | None] | None = None


class InitializeNoCircuit(Initialize1):
    """Simulation Initialize block without reference to the circuit."""

    circuit: SkipJsonSchema[None] = Field(default=None, title="Circuit", exclude=True)  # type: ignore


class CircuitSimulationScanConfigModified(CircuitSimulationScanConfig):
    """Simulations form that redefines certain attributes."""

    initialize: InitializeNoCircuit = Field(
        ...,
        description="Parameters for initializing the simulation.",
        title="Initialization",
    )


class GenerateSimulationsConfigTool(BaseTool):
    """Class defining the GenerateSimulationsConfig tool."""

    name: ClassVar[str] = "obione-generatesimulationsconfig"
    name_frontend: ClassVar[str] = "Generate Simulation Config"
    utterances: ClassVar[list[str]] = [
        "Create a simulation configuration",
        "Generate a config for me",
        "Set up simulation parameters",
    ]
    description: ClassVar[
        str
    ] = """This tool generates JSON configurations for simulations based on natural language descriptions. It accepts both complete configuration specifications and modification requests for existing configurations, using an LLM with structured output to produce the corresponding JSON.
    Always use a circuit ID with this tool. If you can't see a reference to an existing circuit in the chat, ask for clarifications.

For modifications, you can provide incremental change descriptions - the tool will interpret these in the context of the existing configuration. You don't need to describe the entire final state; focused modification requests are fully supported.

Input: Either a comprehensive new configuration description OR specific modifications to an existing configuration
IMPORTANT: In the config_request parameter, only describe what the user explicitly requested. Do NOT include default values or standard parameters - the downstream LLM will handle those automatically. The output will always be valid JSON.
The downstream LLM uses structured output. It has a lot of information about the structure and defaults of the simulations form.

Available configuration fields: {extract_model_structure(SimulationsForm)}

Output: Valid simulation config json

Use this tool when users need to:
- Create new configurations from scratch
- Modify, update, or tweak existing configurations
- Convert configuration requirements into structured JSON format

Always call this tool to generate a simulation config, never attempt to generate one yourself.
Do not try to generate a simulation config yourself if the tool fails.

CRITICAL: DO NOT WRITE THE FINAL JSON OUTPUT IN THE CHAT. It will be automatically taken care of by the platform.
"""
    description_frontend: ClassVar[
        str
    ] = """Create or modify JSON configurations using natural language.
Simply specify in plain english what you want your configuration to achieve or what changes you'd like to make."""
    metadata: GenerateSimulationsConfigMetadata
    input_schema: GenerateSimulationsConfigInput

    async def arun(self) -> CircuitSimulationScanConfig:
        """Run the tool."""
        # Get the available nodesest in the circuit
        headers: dict[str, str] = {}
        if self.metadata.vlab_id is not None:
            headers["virtual-lab-id"] = str(self.metadata.vlab_id)
        if self.metadata.project_id is not None:
            headers["project-id"] = str(self.metadata.project_id)

        circuit_node_set = await self.metadata.httpx_client.get(
            self.metadata.obi_one_url.rstrip("/")
            + f"/declared/circuit/{self.input_schema.circuit_id}/nodesets",
            headers=headers,
        )
        if circuit_node_set.status_code != 200:
            raise ValueError(
                f"The nodesets endpoint returned a non 200 response code. Error: {circuit_node_set.text}"
            )

        # Check for existing state passed by frontend
        if not self.metadata.shared_state:
            raise ValueError(
                "A state with key `smc_simulation_config` must be provided in the request body to trigger this tool."
            )
        base_simulation_form = self.metadata.shared_state.smc_simulation_config
        if base_simulation_form is None:
            raise ValueError(
                f"To edit a Small Microcircuit Simulation, first navigate to {self.metadata.entity_frontend_url + '/simulate?&s=new&t=small-microcircuit'}, pick a circuit, click 'New Simulation' and call the tool again."
            )

        # List obi-one rules
        system_prompt = f"""# Simulation Configuration Generator

You are an expert at generating valid JSON simulation configurations following the CircuitSimulationScanConfig schema.
You will receive two inputs:
1. A description of the required configuration changes or specifications
2. The current simulation configuration JSON (either a default/empty config or an existing one)

## Task Approach
You are always modifying the provided configuration. The nature of modifications depends on the starting point:
- **Starting from default config**: User requests typically describe complete simulation requirements ("Generate a simulation with X neurons for Y duration")
- **Starting from existing config**: User requests typically describe incremental changes ("Add stimulus X", "Set parameter Y to Z")

Apply the requested changes to the provided configuration, replacing or adding elements as needed.

## Timestamps and Stimuli Logic
- **Only generate timestamps if stimuli will use them**
- Choose stimulus type based on timing pattern:
  - **Single timestamp + MultiPulse**: For repeated pulses at one timepoint
  - **Multiple timestamps + single-pulse stimulus**: For stimuli at different timepoints
  - **Never combine MultiPulse with repetitive timestamps**
- Modify existing timing logic only when specifically requested

## Parameter Values
- Use single values, not single-element lists (e.g., `"duration": 500.0` not `"duration": [500.0]`)
- Lists indicate parameter sweeps - only use when scanning multiple values
- For IDNeuronSet, include meaningful number of neurons (typically 50+ for populations)
- Update only the parameters mentioned in the modification request

## Modification Guidelines
- **Comprehensive requests** (from default configs): Build out the full simulation as described, replacing default values
- **Incremental requests** (from existing configs): Make targeted changes while preserving unmodified elements
- "Add X" means include X alongside existing elements (unless it conflicts)
- "Remove" or "delete" means eliminate the specified element entirely
- "Set" or "change" means replace the specified parameter with the new value
- When building from defaults, interpret requests as comprehensive specifications rather than additions

## Neuron Sets and References
- Generate neuron sets in the "neuron_sets" dictionary with meaningful keys
- **Only create neuron sets that will actually be used**
- For references (NeuronSetReference, TimestampsReference):
  - `block_name`: the dictionary key (e.g., "all_neurons")
  - `block_dict_name`: the parent dictionary name (e.g., "neuron_sets", "timestamps")
- Avoid duplicate or unused neuron sets unless specifically requested
- Whenever you see a `circuit_property_type = CircuitNodeSet` in the schema of the neuron_sets you want to use, the string value within `node_set` must be one of the following: {circuit_node_set.json()}

## Validation Checklist
Before outputting, verify:
- [ ] All references use existing dictionary keys with correct block_dict_name
- [ ] No unused neuron sets or timestamps
- [ ] Stimulus timing logic is coherent
- [ ] No single-element lists unless intentional parameter sweep
- [ ] Requested changes are accurately applied to the provided configuration
- [ ] Configuration structure remains valid and consistent

Generate only the JSON configuration, ensuring all references are internally consistent.
"""

        user_message = f"""
CURRENT SIMULATION CONFIG JSON:
{json.dumps(base_simulation_form)}

REQUIREMENTS:
{self.input_schema.config_request}
"""

        model = "gpt-5-mini"
        # Then generate the global class and make the according references
        response = await self.metadata.openai_client.beta.chat.completions.parse(
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_message},
            ],
            model=model,
            reasoning_effort="low",
            response_format=CircuitSimulationScanConfigModified,
        )
        if response.choices[0].message.parsed:
            # Get the output config
            config = response.choices[0].message.parsed

            # Gather everything in the OBI-One compatible class
            output_config = CircuitSimulationScanConfig(
                type="CircuitSimulationScanConfig",
                timestamps=config.timestamps or {},
                stimuli=config.stimuli or {},
                recordings=config.recordings or {},
                neuron_sets=config.neuron_sets or {},
                synaptic_manipulations=config.synaptic_manipulations or {},
                initialize=Initialize1(
                    circuit=CircuitFromID(
                        id_str=str(self.input_schema.circuit_id), type="CircuitFromID"
                    ),
                    **config.initialize.model_dump(),
                ),
                info=config.info,
            )

            # Assign token usage
            token_consumption = get_token_count(response.usage)
            self.metadata.token_consumption = {**token_consumption, "model": model}
        else:
            raise ValueError("Couldn't generate a valid simulation config.")
        return ts_number_normalize(output_config)

    @classmethod
    async def is_online(cls) -> bool:
        """Check if the tool is online."""
        return True


def ts_number_normalize(value: Any) -> Any:
    """Cast python json to ts json."""
    if isinstance(value, float):
        return int(value) if value.is_integer() else value
    if isinstance(value, list):
        return [ts_number_normalize(v) for v in value]
    if isinstance(value, dict):
        return {k: ts_number_normalize(v) for k, v in value.items()}
    return value
