"""Obi-one circuit population tool."""

from typing import ClassVar
from uuid import UUID

from httpx import AsyncClient
from pydantic import BaseModel, Field

from neuroagent.tools.autogenerated_types.obione import CircuitPopulationsResponse
from neuroagent.tools.base_tool import BaseMetadata, BaseTool


class CircuitPopulationGetOneToolInput(BaseModel):
    """Input class of the circuit population tool."""

    circuit_id: UUID = Field(
        description="ID of the circuit from which the population should be retrieved."
    )


class CircuitPopulationGetOneToolMetadata(BaseMetadata):
    """Metadata class of the circuit population tool."""

    httpx_client: AsyncClient
    obi_one_url: str
    vlab_id: UUID | None
    project_id: UUID | None


class CircuitPopulationGetOneTool(BaseTool):
    """Tool to get the circuit population."""

    name: ClassVar[str] = "obione-circuitpopulation-getone"
    name_frontend: ClassVar[str] = "Get Circuit Population"
    utterances: ClassVar[list[str]] = [
        "Get the circuit population",
        "Retrieve population data for this circuit",
        "Show me the population of this circuit",
    ]
    description: ClassVar[str] = "Given a circuit ID, retrieve the population of it."
    description_frontend: ClassVar[str] = (
        """Retrieve the population data for a circuit, and get insights into its composition."""
    )
    metadata: CircuitPopulationGetOneToolMetadata
    input_schema: CircuitPopulationGetOneToolInput

    async def arun(self) -> CircuitPopulationsResponse:
        """Run the circuit population retrieval."""
        headers: dict[str, str] = {}
        if self.metadata.vlab_id is not None:
            headers["virtual_lab_id"] = str(self.metadata.vlab_id)
        if self.metadata.project_id is not None:
            headers["project_id"] = str(self.metadata.project_id)

        circuit_population_response = await self.metadata.httpx_client.get(
            url=f"{self.metadata.obi_one_url}/declared/circuit/{self.input_schema.circuit_id}/biophysical_populations",
            headers=headers,
        )

        if circuit_population_response.status_code != 200:
            raise ValueError(
                f"The circuit population endpoint returned a non 200 response code. Error: {circuit_population_response.text}"
            )
        return CircuitPopulationsResponse(**circuit_population_response.json())

    @classmethod
    async def is_online(cls, *, httpx_client: AsyncClient, obi_one_url: str) -> bool:
        """Check if the tool is online."""
        response = await httpx_client.get(
            f"{obi_one_url.rstrip('/')}/health",
        )
        return response.status_code == 200
