"""Get One Morphology Thumbnail tool."""

from typing import Any, ClassVar
from uuid import UUID

from httpx import AsyncClient
from pydantic import BaseModel, Field
from pydantic.json_schema import SkipJsonSchema

from neuroagent.tools.autogenerated_types.thumbnail_generation import (
    GetMorphologyPreviewApiThumbnailGenerationCoreCellMorphologyPreviewGetParametersQuery,
)
from neuroagent.tools.base_tool import BaseMetadata, BaseTool
from neuroagent.utils import save_to_storage


class PlotMorphologyGetOneInput(
    GetMorphologyPreviewApiThumbnailGenerationCoreCellMorphologyPreviewGetParametersQuery
):
    """Input of the PlotMorphologyGetOneTool."""

    asset_id: SkipJsonSchema[None] = Field(default=None, exclude=True)  # type: ignore


class PlotMorphologyGetOneMetadata(BaseMetadata):
    """Metadata class for the thumbnail generation of morphologies."""

    httpx_client: AsyncClient
    thumbnail_generation_url: str
    entitycore_url: str
    s3_client: Any  # boto3 client
    user_id: UUID
    bucket_name: str
    thread_id: UUID
    vlab_id: UUID | None
    project_id: UUID | None
    storage_frontend_url: str


class PlotMorphologyGetOneOutput(BaseModel):
    """Output of the PlotMorphologyGetOneTool."""

    image_link: str


class PlotMorphologyGetOneTool(BaseTool):
    """Class defining the Get One Morphology Thumbnail logic."""

    name: ClassVar[str] = "thumbnail-generation-morphology-getone"
    name_frontend: ClassVar[str] = "Get Morphology Thumbnail"
    utterances: ClassVar[list[str]] = [
        "Create a visual representation",
        "Generate a thumbnail for this morphology",
        "Show me a visualization of this morphology",
    ]
    description: ClassVar[str] = """**Purpose**:
        Generate a visual representation of a specified morphology.

        **When to Call**:
        When the user asks to plot a morphology or requests more information about a morphology.

        **Inputs**:
        entity_id: ID of the target entity.

        **Output**:
        storage_id: Identifier for where the generated plot is stored.
        image_link: URL to the stored plot image that should be embedded as an image in responses.
    """
    description_frontend: ClassVar[
        str
    ] = """Plot the morphology of your choice to display a thumbnail in the chat.

    Use this tool to enhance the description of your target morphology by adding visuals."""
    metadata: PlotMorphologyGetOneMetadata
    input_schema: PlotMorphologyGetOneInput

    async def arun(self) -> PlotMorphologyGetOneOutput:
        """From an Entity ID and an Asset ID, plot the visual of the morphology.

        Returns
        -------
            storage_id which locates the plot in the storage.
        """
        headers: dict[str, str] = {}
        if self.metadata.vlab_id is not None:
            headers["virtual-lab-id"] = str(self.metadata.vlab_id)
        if self.metadata.project_id is not None:
            headers["project-id"] = str(self.metadata.project_id)

        # Retrieve the asset_id from the entity_id
        cell_morphology = await self.metadata.httpx_client.get(
            url=self.metadata.entitycore_url.rstrip("/")
            + f"/cell-morphology/{self.input_schema.entity_id}",
            headers=headers,
        )
        if cell_morphology.status_code != 200:
            raise ValueError(
                f"The Cell Morphology endpoint returned a non 200 response code. Error: {cell_morphology.text}"
            )
        assets = cell_morphology.json()["assets"]

        # Get the nwb asset
        swc_asset = next(
            (asset for asset in assets if asset["content_type"] == "application/swc"),
            None,
        )
        if not swc_asset:
            raise ValueError(
                f"No NWB asset found for the electrical cell recording {self.input_schema.entity_id}"
            )

        query_params = self.input_schema.model_dump(exclude_defaults=True, mode="json")
        query_params["asset_id"] = swc_asset["id"]

        response = await self.metadata.httpx_client.get(
            url=self.metadata.thumbnail_generation_url.rstrip("/")
            + "/core/cell-morphology/preview",
            headers=headers,
            params=query_params,
        )
        if response.status_code != 200:
            raise ValueError(
                f"The Morphology Thumbnail endpoint returned a non 200 response code. Error: {response.text}"
            )

        # Save to storage
        identifier = save_to_storage(
            s3_client=self.metadata.s3_client,
            bucket_name=self.metadata.bucket_name,
            user_id=self.metadata.user_id,
            content_type="image/png",
            category="image",
            body=response.content,
            thread_id=self.metadata.thread_id,
        )

        url = f"{self.metadata.storage_frontend_url}/{identifier}"
        return PlotMorphologyGetOneOutput(image_link=url)

    @classmethod
    async def is_online(
        cls, *, httpx_client: AsyncClient, thumbnail_generation_url: str
    ) -> bool:
        """Check if the tool is online."""
        response = await httpx_client.get(
            f"{thumbnail_generation_url.rstrip('/')}/health",
        )
        return response.status_code == 200
