"""Shared state types."""

from typing import Any

from pydantic import BaseModel

from neuroagent.autogenerated_types.obione import CircuitSimulationScanConfig


class SharedStateStrict(BaseModel):
    """Eventually for saving to DBs."""

    smc_simulation_config: CircuitSimulationScanConfig


class SharedStatePartial(BaseModel):
    """For validation and schema dumping."""

    smc_simulation_config: CircuitSimulationScanConfig | None = None


class SharedStateLoosened(BaseModel):
    """For request body and tool outputs."""

    smc_simulation_config: dict[str, Any] | None = None
