"""Shared state types."""

from typing import Any

from pydantic import BaseModel

from neuroagent.autogenerated_types.obione import CircuitSimulationScanConfig


class SharedStatePartial(BaseModel):
    """State shared between backend and frontend."""

    smc_simulation_config: dict[str, Any] | None = None


class SharedStateStrict(BaseModel):
    """State shared between backend and frontend."""

    smc_simulation_config: CircuitSimulationScanConfig | None = None
