/**
 * Asset GetAll Tool
 *
 * Translated from backend/src/neuroagent/tools/entitycore_asset_getall.py
 *
 * Retrieves all assets from the entitycore service.
 */

import { z } from 'zod';
import { HTTPError } from 'ky';

import { BaseTool, type EntitycoreContextVariables } from '../base-tool';
import {
  zEntityRoute,
  zListResponseAssetRead,
} from '../autogenerated_types/entitycore/zod.gen';

/**
 * Input schema for Asset GetAll tool
 *
 * Requires entity_route and entity_id to retrieve assets for a specific entity.
 *
 * Equivalent to Python's AssetGetAllInputSchema
 */
const AssetGetAllInputSchema = z.object({
  entity_route: zEntityRoute.describe('The route of the entity'),
  entity_id: z
    .string()
    .uuid()
    .describe(
      'The ID of the entity. Must be the UUID of the entity you want to retrieve the assets from.'
    ),
});

/**
 * Asset GetAll Tool
 *
 * Retrieves all assets for a specific entity from the EntityCore service.
 * Assets can include files, directories, and other data associated with an entity.
 */
export class AssetGetAllTool extends BaseTool<
  typeof AssetGetAllInputSchema,
  EntitycoreContextVariables
> {
  // Static properties (tool metadata)
  static readonly toolName = 'entitycore-asset-getall';
  static readonly toolNameFrontend = 'Get All Assets';
  static readonly toolDescription = `Retrieves all assets from the entitycore service.
The output contains a list of assets, each containing:
- The asset path
- The asset full path
- Whether it's a directory
- Content type
- Size
- SHA256 digest
- Metadata
- Label
- ID
- Status`;
  static readonly toolDescriptionFrontend = `Retrieve all assets. Use this tool to:
• Get a list of all assets for an entity
• Filter assets by ID
• Access asset metadata and properties

Specify the entity route and entity ID to retrieve the assets.`;
  static readonly toolUtterances = [
    'List all files for this entity',
    'Show me all assets',
    'What assets are available?',
  ];
  static readonly toolHil = false;

  override contextVariables: EntitycoreContextVariables;
  override inputSchema = AssetGetAllInputSchema;

  constructor(contextVariables: EntitycoreContextVariables) {
    super();
    this.contextVariables = contextVariables;
  }

  /**
   * Execute the asset retrieval
   *
   * @param input - Validated input with entity_route and entity_id
   * @returns List of assets with metadata
   */
  async execute(
    input: z.infer<typeof AssetGetAllInputSchema>
  ): Promise<z.infer<typeof zListResponseAssetRead>> {
    const { entitycoreUrl, vlabId, projectId, httpClient } = this.contextVariables;

    // Prepare headers
    const headers: Record<string, string> = {};
    if (vlabId) {
      headers['virtual-lab-id'] = vlabId;
    }
    if (projectId) {
      headers['project-id'] = projectId;
    }

    try {
      const url = `${entitycoreUrl.replace(/\/$/, '')}/${input.entity_route}/${input.entity_id}/assets`;

      // Use ky's built-in JSON parsing and error handling
      const data = await httpClient
        .get(url, {
          headers,
        })
        .json();

      // Validate response with Zod schema
      const validated = zListResponseAssetRead.parse(data);
      return validated;
    } catch (error) {
      if (error instanceof HTTPError) {
        const { status, statusText } = error.response;
        let responseBody = '';
        try {
          responseBody = await error.response.text();
        } catch {
          // Ignore if we can't read the body
        }
        throw new Error(
          `The The asset endpoint returned a non 200 response code. Error: ${status} ${statusText}${responseBody ? ': ' + responseBody : ''}`
        );
      }
      throw error;
    }
  }

  /**
   * Static health check method (classmethod equivalent)
   *
   * @param contextVariables - Context variables with API configuration
   * @returns True if the service is online
   */
  static async isOnline(contextVariables: EntitycoreContextVariables): Promise<boolean> {
    try {
      const { entitycoreUrl, httpClient } = contextVariables;
      const healthUrl = `${entitycoreUrl.replace(/\/$/, '')}/health`;

      await httpClient.get(healthUrl);
      return true;
    } catch {
      return false;
    }
  }
}
