/**
 * Asset DownloadOne Tool
 *
 * Translated from backend/src/neuroagent/tools/entitycore_asset_downloadone.py
 *
 * Retrieves a presigned URL for downloading a single asset from the entitycore service.
 */

import { z } from 'zod';
import { HTTPError } from 'ky';

import { BaseTool, type EntitycoreContextVariables } from '../base-tool';
import { zEntityRoute } from '../autogenerated_types/entitycore/zod.gen';

/**
 * Input schema for Asset DownloadOne tool
 *
 * Requires entity_route, entity_id, and asset_id to get a download URL.
 *
 * Equivalent to Python's AssetDownloadOneInputSchema
 */
const AssetDownloadOneInputSchema = z.object({
  entity_route: zEntityRoute.describe('The route of the entity'),
  entity_id: z.string().uuid().describe('The ID of the entity'),
  asset_id: z.string().uuid().describe('The ID of the asset'),
});

/**
 * Output schema for Asset DownloadOne tool
 *
 * Contains the presigned URL for downloading the asset.
 *
 * Equivalent to Python's AssetDownloadOneOutput
 */
const AssetDownloadOneOutputSchema = z.object({
  presigned_url: z.string().describe('The presigned URL for downloading the asset'),
});

/**
 * Asset DownloadOne Tool
 *
 * Retrieves a presigned URL for downloading a specific asset from the EntityCore service.
 * The presigned URL can be used to download the asset content directly.
 */
export class AssetDownloadOneTool extends BaseTool<
  typeof AssetDownloadOneInputSchema,
  EntitycoreContextVariables
> {
  // Static properties (tool metadata)
  static readonly toolName = 'entitycore-asset-downloadone';
  static readonly toolNameFrontend = 'Download One Asset';
  static readonly toolDescription = `Retrieves a presigned URL for downloading a single asset from the entitycore service.
The output contains:
- A presigned URL that can be used to download the asset`;
  static readonly toolDescriptionFrontend = `Download a single asset. Use this tool to:
• Get a download link for a specific asset
• Access the asset content directly

Specify the entity route and entity ID to get the download URL.`;
  static readonly toolUtterances = [
    'Download this asset',
    'Get download link for the file',
    'I need to download this data',
  ];

  override contextVariables: EntitycoreContextVariables;
  override inputSchema = AssetDownloadOneInputSchema;

  constructor(contextVariables: EntitycoreContextVariables) {
    super();
    this.contextVariables = contextVariables;
  }

  /**
   * Execute the download URL retrieval
   *
   * @param input - Validated input with entity_route, entity_id, and asset_id
   * @returns Presigned URL for downloading the asset
   */
  async execute(
    input: z.infer<typeof AssetDownloadOneInputSchema>
  ): Promise<z.infer<typeof AssetDownloadOneOutputSchema>> {
    const { entitycoreUrl, vlabId, projectId, httpClient } = this.contextVariables;

    // Prepare headers
    const headers: Record<string, string> = {};
    if (vlabId) {
      headers['virtual-lab-id'] = vlabId;
    }
    if (projectId) {
      headers['project-id'] = projectId;
    }

    try {
      const url = `${entitycoreUrl.replace(/\/$/, '')}/${input.entity_route}/${input.entity_id}/assets/${input.asset_id}/download`;

      // Use ky with redirect: 'manual' to get the redirect location
      // The Python version expects a 307 redirect with the presigned URL in the Location header
      await httpClient.get(url, {
        headers,
        redirect: 'manual', // Don't follow redirects automatically
      });

      // If we reach here, we got a 2xx response instead of a redirect
      // This is unexpected, so throw an error
      throw new Error('Expected 307 redirect response but got success response');
    } catch (error) {
      if (error instanceof HTTPError) {
        const { status, statusText } = error.response;

        // Check if this is the expected 307 redirect
        if (status === 307) {
          const location = error.response.headers.get('location');
          if (!location) {
            throw new Error(
              'The asset download endpoint returned a 307 redirect but no Location header was found.'
            );
          }
          return { presigned_url: location };
        }

        // If it's not a 307, it's an error - match Python's error format
        let responseBody = '';
        try {
          responseBody = await error.response.text();
        } catch {
          // Ignore if we can't read the body
        }
        throw new Error(
          `The asset download endpoint returned a non 307 response code. Error: ${responseBody || `${status} ${statusText}`}`
        );
      }
      throw error;
    }
  }

  /**
   * Static health check method (classmethod equivalent)
   *
   * @param contextVariables - Context variables with API configuration
   * @returns True if the service is online
   */
  static async isOnline(contextVariables: EntitycoreContextVariables): Promise<boolean> {
    try {
      const { entitycoreUrl, httpClient } = contextVariables;
      const healthUrl = `${entitycoreUrl.replace(/\/$/, '')}/health`;

      await httpClient.get(healthUrl);
      return true;
    } catch {
      return false;
    }
  }
}
