/**
 * Circuit GetOne Tool
 *
 * Translated from backend/src/neuroagent/tools/entitycore_circuit_getone.py
 *
 * Retrieves detailed information about a specific circuit from the knowledge graph.
 */

import { z } from 'zod';

import { BaseTool, type EntitycoreContextVariables } from '../base-tool';
import { zReadOneCircuitIdGetResponse } from '../autogenerated_types/entitycore.ts/zod.gen';

/**
 * Input schema for Circuit GetOne tool
 *
 * Requires a circuit_id to retrieve detailed information about a specific circuit.
 */
const CircuitGetOneInputSchema = z.object({
  circuit_id: z.string().uuid().describe('ID of the circuit of interest in UUID format.'),
});

/**
 * Circuit GetOne Tool
 *
 * Retrieves detailed information about a specific circuit from the EntityCore knowledge graph.
 *
 * Use this for basic circuit info only. For detailed analysis, use:
 * - `obione-circuitmetrics-getone` - circuit structure and properties
 * - `obione-circuitconnectivitymetrics-getone` - connectivity patterns
 */
export class CircuitGetOneTool extends BaseTool<
  typeof CircuitGetOneInputSchema,
  EntitycoreContextVariables
> {
  // Static properties (tool metadata)
  static readonly toolName = 'entitycore-circuit-getone';
  static readonly toolNameFrontend = 'Get One Circuit';
  static readonly toolDescription = `Get basic circuit metadata (name, ID, status, timestamps).

Use this for basic circuit info only. For detailed analysis, use:
- \`obione-circuitmetrics-getone\` - circuit structure and properties
- \`obione-circuitconnectivitymetrics-getone\` - connectivity patterns`;
  static readonly toolDescriptionFrontend = `Get basic circuit metadata (name, ID, status, timestamps).`;
  static readonly toolUtterances = [
    'Get details for this circuit',
    'Show me information about this circuit',
    'What are the properties of this circuit?',
  ];
  static readonly toolHil = false;

  override contextVariables: EntitycoreContextVariables;
  override inputSchema = CircuitGetOneInputSchema;

  constructor(contextVariables: EntitycoreContextVariables) {
    super();
    this.contextVariables = contextVariables;
  }

  /**
   * Execute the circuit retrieval
   *
   * @param input - Validated input with circuit_id
   * @returns Detailed circuit information
   */
  async execute(
    input: z.infer<typeof CircuitGetOneInputSchema>
  ): Promise<z.infer<typeof zReadOneCircuitIdGetResponse>> {
    const { entitycoreUrl, vlabId, projectId, httpClient, entityFrontendUrl } =
      this.contextVariables;

    // Prepare headers
    const headers: Record<string, string> = {};
    if (vlabId) {
      headers['virtual-lab-id'] = vlabId;
    }
    if (projectId) {
      headers['project-id'] = projectId;
    }

    try {
      const url = `${entitycoreUrl.replace(/\/$/, '')}/circuit/${input.circuit_id}`;

      // Use ky's built-in JSON parsing and error handling
      const data = await httpClient
        .get(url, {
          headers,
        })
        .json<any>();

      // Add the link to website
      data.url_link = `${entityFrontendUrl}/${data.id}`;

      // Validate response with Zod schema
      const validated = zReadOneCircuitIdGetResponse.parse(data);
      return validated;
    } catch (error: any) {
      throw new Error(
        `The circuit endpoint returned an error: ${error.message || JSON.stringify(error)}`
      );
    }
  }

  /**
   * Static health check method (classmethod equivalent)
   *
   * @param contextVariables - Context variables with API configuration
   * @returns True if the service is online
   */
  static async isOnline(contextVariables: EntitycoreContextVariables): Promise<boolean> {
    try {
      const { entitycoreUrl, httpClient } = contextVariables;
      const healthUrl = `${entitycoreUrl.replace(/\/$/, '')}/health`;

      await httpClient.get(healthUrl);
      return true;
    } catch {
      return false;
    }
  }
}
