/**
 * EModel GetOne Tool
 *
 * Translated from backend/src/neuroagent/tools/entitycore_emodel_getone.py
 *
 * Retrieves detailed information about a specific e-model from the knowledge graph.
 */

import { z } from 'zod';
import { HTTPError } from 'ky';

import { BaseTool, type EntitycoreContextVariables } from '../base-tool';
import { zReadOneEmodelIdGetResponse } from '../autogenerated_types/entitycore/zod.gen';

/**
 * Input schema for EModel GetOne tool
 *
 * Requires an emodel_id to retrieve detailed information about a specific e-model.
 */
const EModelGetOneInputSchema = z.object({
  emodel_id: z.string().uuid().describe('ID of the e-model of interest in UUID format.'),
});

/**
 * EModel GetOne Tool
 *
 * Retrieves detailed information about a specific e-model from the EntityCore knowledge graph.
 */
export class EModelGetOneTool extends BaseTool<
  typeof EModelGetOneInputSchema,
  EntitycoreContextVariables
> {
  // Static properties (tool metadata)
  static readonly toolName = 'entitycore-emodel-getone';
  static readonly toolNameFrontend = 'Get One E-Model';
  static readonly toolDescription = `Retrieves detailed information about a specific e-model from the knowledge graph.
Requires an 'emodel_id' which is the ID of the e-model of interest as registered in the knowledge graph.
The output contains detailed information about the e-model, including:
- The e-model ID
- The e-model name
- The e-model description
- The e-model iteration
- The e-model score
- The associated species
- The associated brain region
- The associated e-types and m-types
- Creation and update date
- Assets
- Ion channel models`;
  static readonly toolDescriptionFrontend = `Get detailed information about a specific e-model. Use this tool to:
• View complete e-model details
• Access associated metadata
• Get species and brain region information
• View associated e-types and m-types

Specify the e-model ID to retrieve its full details.`;
  static readonly toolUtterances = [
    'Get details for this e-model',
    'Show me information about this e-model',
    'What are the properties of this e-model?',
  ];

  override contextVariables: EntitycoreContextVariables;
  override inputSchema = EModelGetOneInputSchema;

  constructor(contextVariables: EntitycoreContextVariables) {
    super();
    this.contextVariables = contextVariables;
  }

  /**
   * Execute the e-model retrieval
   *
   * @param input - Validated input with emodel_id
   * @returns Detailed e-model information
   */
  async execute(
    input: z.infer<typeof EModelGetOneInputSchema>
  ): Promise<z.infer<typeof zReadOneEmodelIdGetResponse>> {
    const { entitycoreUrl, vlabId, projectId, httpClient, entityFrontendUrl } =
      this.contextVariables;

    // Prepare headers
    const headers: Record<string, string> = {};
    if (vlabId) {
      headers['virtual-lab-id'] = vlabId;
    }
    if (projectId) {
      headers['project-id'] = projectId;
    }

    try {
      const url = `${entitycoreUrl.replace(/\/$/, '')}/emodel/${input.emodel_id}`;

      // Use ky's built-in JSON parsing and error handling
      const data = await httpClient
        .get(url, {
          headers,
        })
        .json<any>();

      // Add the link to website
      data.url_link = `${entityFrontendUrl}/${data.id}`;

      // Validate response with Zod schema
      const validated = zReadOneEmodelIdGetResponse.parse(data);
      return validated;
    } catch (error) {
      if (error instanceof HTTPError) {
        const { status, statusText } = error.response;
        let responseBody = '';
        try {
          responseBody = await error.response.text();
        } catch {
          // Ignore if we can't read the body
        }
        throw new Error(
          `The emodel endpoint returned a non 200 response code. Error: ${status} ${statusText}${responseBody ? ': ' + responseBody : ''}`
        );
      }
      throw error;
    }
  }

  /**
   * Static health check method (classmethod equivalent)
   *
   * @param contextVariables - Context variables with API configuration
   * @returns True if the service is online
   */
  static async isOnline(contextVariables: EntitycoreContextVariables): Promise<boolean> {
    try {
      const { entitycoreUrl, httpClient } = contextVariables;
      const healthUrl = `${entitycoreUrl.replace(/\/$/, '')}/health`;

      await httpClient.get(healthUrl);
      return true;
    } catch {
      return false;
    }
  }
}
