/**
 * Experimental Neuron Density GetOne Tool
 *
 * Translated from backend/src/neuroagent/tools/entitycore_experimentalneurondensity_getone.py
 *
 * Retrieves detailed information about a specific experimental neuron density from the knowledge graph.
 */

import { z } from 'zod';

import { BaseTool, type EntitycoreContextVariables } from '../base-tool';
import { zExperimentalNeuronDensityRead } from '../autogenerated_types/entitycore.ts/zod.gen';

/**
 * Input schema for Experimental Neuron Density GetOne tool
 *
 * Requires a density_id to retrieve specific neuron density details.
 *
 * Equivalent to Python's ExperimentalNeuronDensityGetOneInput
 */
const ExperimentalNeuronDensityGetOneInputSchema = z.object({
  density_id: z
    .string()
    .uuid()
    .describe('ID of the experimental neuron density of interest in UUID format.'),
});

/**
 * Experimental Neuron Density GetOne Tool
 *
 * Retrieves detailed information about a specific experimental neuron density
 * from the EntityCore knowledge graph.
 */
export class ExperimentalNeuronDensityGetOneTool extends BaseTool<
  typeof ExperimentalNeuronDensityGetOneInputSchema,
  EntitycoreContextVariables
> {
  // Static properties (tool metadata)
  static readonly toolName = 'entitycore-experimentalneurondensity-getone';
  static readonly toolNameFrontend = 'Get One Experimental Neuron Density';
  static readonly toolDescription = `Retrieves detailed information about a specific experimental neuron density from the knowledge graph.
Requires a 'density_id' which is the ID of the density of interest as registered in the knowledge graph.
The output contains detailed information about the density, including:
- The density ID (it is the \`id\` field in the response - ignore other IDs)
- The density name
- The density description
- Associated brain region information
- Subject species information
- Associated measurements
- Associated assets
- Associated contributions
- Associated mtypes and etypes`;
  static readonly toolDescriptionFrontend = `Get detailed information about a specific experimental neuron density. Use this tool to:
• View complete density details
• Access associated metadata
• Get brain region and species information

Specify the density ID to retrieve its full details.`;
  static readonly toolUtterances = [
    'Get details for this neuron density',
    'Show me information about this neuron density',
    'What are the properties of this experimental neuron density?',
  ];
  static readonly toolHil = false;

  override contextVariables: EntitycoreContextVariables;
  override inputSchema = ExperimentalNeuronDensityGetOneInputSchema;

  constructor(contextVariables: EntitycoreContextVariables) {
    super();
    this.contextVariables = contextVariables;
  }

  /**
   * Execute the experimental neuron density retrieval
   *
   * @param input - Validated input with density_id
   * @returns Detailed experimental neuron density information
   */
  async execute(
    input: z.infer<typeof ExperimentalNeuronDensityGetOneInputSchema>
  ): Promise<z.infer<typeof zExperimentalNeuronDensityRead>> {
    const { entitycoreUrl, vlabId, projectId, httpClient, entityFrontendUrl } =
      this.contextVariables;

    // Prepare headers
    const headers: Record<string, string> = {};
    if (vlabId) {
      headers['virtual-lab-id'] = vlabId;
    }
    if (projectId) {
      headers['project-id'] = projectId;
    }

    try {
      const url = `${entitycoreUrl.replace(/\/$/, '')}/experimental-neuron-density/${input.density_id}`;

      // Use ky's built-in JSON parsing and error handling
      const data = await httpClient
        .get(url, {
          headers,
        })
        .json<any>();

      // Add the link to the entity frontend
      data.url_link = `${entityFrontendUrl}/${data.id}`;

      // Validate response with Zod schema
      const validated = zExperimentalNeuronDensityRead.parse(data);
      return validated;
    } catch (error: any) {
      throw new Error(
        `The experimental neuron density endpoint returned an error: ${error.message || JSON.stringify(error)}`
      );
    }
  }

  /**
   * Static health check method (classmethod equivalent)
   *
   * @param contextVariables - Context variables with API configuration
   * @returns True if the service is online
   */
  static async isOnline(contextVariables: EntitycoreContextVariables): Promise<boolean> {
    try {
      const { entitycoreUrl, httpClient } = contextVariables;
      const healthUrl = `${entitycoreUrl.replace(/\/$/, '')}/health`;

      await httpClient.get(healthUrl);
      return true;
    } catch {
      return false;
    }
  }
}
