/**
 * Ion Channel Model GetOne Tool
 *
 * Translated from backend/src/neuroagent/tools/entitycore_ionchannelmodel_getone.py
 *
 * Retrieves detailed information about a specific ion channel model from the knowledge graph.
 */

import { z } from 'zod';
import { HTTPError } from 'ky';

import { BaseTool, type EntitycoreContextVariables } from '../base-tool';
import { zIonChannelModelRead } from '../autogenerated_types/entitycore/zod.gen';

/**
 * Input schema for Ion Channel Model GetOne tool
 */
const IonChannelModelGetOneInputSchema = z.object({
  ion_channel_model_id: z
    .string()
    .uuid()
    .describe('ID of the ion channel model of interest in UUID format.'),
});

/**
 * Ion Channel Model GetOne Tool
 *
 * Retrieves detailed information about a specific ion channel model,
 * including all metadata, assets, contributions, and measurements.
 */
export class IonChannelModelGetOneTool extends BaseTool<
  typeof IonChannelModelGetOneInputSchema,
  EntitycoreContextVariables
> {
  // Static properties (tool metadata)
  static readonly toolName = 'entitycore-ionchannelmodel-getone';
  static readonly toolNameFrontend = 'Get One Ion Channel Model';
  static readonly toolDescription = `Retrieves detailed information about a specific ion channel model from the knowledge graph.
Requires an 'ion_channel_model_id' which is the ID of the ion channel model of interest as registered in the knowledge graph.
The output contains detailed information about the ion channel model, including:
- The ion channel model ID
- The ion channel model name
- The ion channel model description
- The subject information
- The measurements
- The assets
- The contributions
- The brain region information
- The mtypes
- Any additional metadata`;
  static readonly toolDescriptionFrontend = `Get detailed information about a specific ion channel model. Use this tool to:
• View complete ion channel model details
• Access associated metadata
• Get brain region and subject information
• Access ion channel model assets and measurements

Specify the ion channel model ID to retrieve its full details.`;
  static readonly toolUtterances = [
    'Get details for this ion channel model',
    'Show me information about this ion channel model',
    'What are the properties of this ion channel model?',
  ];
  static readonly toolHil = false;

  override contextVariables: EntitycoreContextVariables;
  override inputSchema = IonChannelModelGetOneInputSchema;

  constructor(contextVariables: EntitycoreContextVariables) {
    super();
    this.contextVariables = contextVariables;
  }

  /**
   * Execute the ion channel model retrieval
   *
   * @param input - Validated input with ion_channel_model_id
   * @returns Detailed ion channel model information
   */
  async execute(
    input: z.infer<typeof IonChannelModelGetOneInputSchema>
  ): Promise<z.infer<typeof zIonChannelModelRead>> {
    const { entitycoreUrl, vlabId, projectId, httpClient, entityFrontendUrl } =
      this.contextVariables;

    // Prepare headers
    const headers: Record<string, string> = {};
    if (vlabId) {
      headers['virtual-lab-id'] = vlabId;
    }
    if (projectId) {
      headers['project-id'] = projectId;
    }

    try {
      const url = `${entitycoreUrl.replace(/\/$/, '')}/ion-channel-model/${input.ion_channel_model_id}`;

      // Use ky's built-in JSON parsing and error handling
      const data = await httpClient
        .get(url, {
          headers,
        })
        .json<any>();

      // Add the link to website
      data.url_link = `${entityFrontendUrl}/${data.id}`;

      // Validate response with Zod schema
      const validated = zIonChannelModelRead.parse(data);
      return validated;
    } catch (error) {
      if (error instanceof HTTPError) {
        const { status, statusText } = error.response;
        let responseBody = '';
        try {
          responseBody = await error.response.text();
        } catch {
          // Ignore if we can't read the body
        }
        throw new Error(
          `The ion channel model endpoint returned a non 200 response code. Error: ${status} ${statusText}${responseBody ? ': ' + responseBody : ''}`
        );
      }
      throw error;
    }
  }

  /**
   * Static health check method (classmethod equivalent)
   *
   * @param contextVariables - Context variables with API configuration
   * @returns True if the service is online
   */
  static async isOnline(contextVariables: EntitycoreContextVariables): Promise<boolean> {
    try {
      const { entitycoreUrl, httpClient } = contextVariables;
      const healthUrl = `${entitycoreUrl.replace(/\/$/, '')}/health`;

      await httpClient.get(healthUrl);
      return true;
    } catch {
      return false;
    }
  }
}
