/**
 * Ion Channel Recording GetOne Tool
 *
 * Translated from backend/src/neuroagent/tools/entitycore_ionchannelrecording_getone.py
 *
 * Retrieves detailed information about a specific ion channel recording.
 */

import { z } from 'zod';
import { HTTPError } from 'ky';

import { BaseTool, type EntitycoreContextVariables } from '../base-tool';
import {
  zReadOneIonChannelRecordingIdGetData,
  zIonChannelRecordingRead,
} from '../autogenerated_types/entitycore/zod.gen';

/**
 * Input schema for Ion Channel Recording GetOne tool
 *
 * Extracts the path parameter schema from the autogenerated types.
 * Equivalent to Python's IonChannelRecordingGetOneInput
 */
const IonChannelRecordingGetOneInputSchema =
  zReadOneIonChannelRecordingIdGetData.shape.path.extend({
    // Rename id_ to ion_channel_recording_id for consistency with Python
    ion_channel_recording_id: z
      .string()
      .uuid()
      .describe('ID of the ion-channel-recording of interest in UUID format.'),
  }).omit({
    id_: true, // Remove the original id_ field
  });

/**
 * Ion Channel Recording GetOne Tool
 *
 * Retrieves detailed information about a specific ion channel recording from the EntityCore knowledge graph.
 */
export class IonChannelRecordingGetOneTool extends BaseTool<
  typeof IonChannelRecordingGetOneInputSchema,
  EntitycoreContextVariables
> {
  // Static properties (tool metadata)
  static readonly toolName = 'entitycore-ionchannelrecording-getone';
  static readonly toolNameFrontend = 'Get One Ion Channel Recording';
  static readonly toolDescription = `Retrieves detailed information about a specific ion-channel-recording from the knowledge graph.
Requires a 'ion_channel_recording_id' which is the ID of the ion-channel-recording of interest as registered in the knowledge graph.
The output contains detailed information about the ion-channel-recording, including:
- The ion channel recording ID and basic identifiers
- Core ion channel recording information and properties
- Status and state information
- Associated metadata and relationships
- Creation and modification timestamps
- Creation and update dates`;
  static readonly toolDescriptionFrontend = `Get detailed information about a specific ion-channel-recording. Use this tool to:
• View complete ion-channel-recording details
• Access detailed ion-channel-recording information
• Get creation and update information

Specify the ion-channel-recording ID to retrieve its full details.`;
  static readonly toolUtterances = [
    'Get ion channel recording details',
    'Show me this ion channel recording',
    'What is this ion channel recording?',
    'Get information about ion channel recording',
  ];

  override contextVariables: EntitycoreContextVariables;
  override inputSchema = IonChannelRecordingGetOneInputSchema;

  constructor(contextVariables: EntitycoreContextVariables) {
    super();
    this.contextVariables = contextVariables;
  }

  /**
   * Execute the ion channel recording retrieval
   *
   * @param input - Validated input containing ion_channel_recording_id
   * @returns Detailed ion channel recording information
   */
  async execute(
    input: z.infer<typeof IonChannelRecordingGetOneInputSchema>
  ): Promise<z.infer<typeof zIonChannelRecordingRead>> {
    const { entitycoreUrl, vlabId, projectId, httpClient, entityFrontendUrl } =
      this.contextVariables;

    // Prepare headers
    const headers: Record<string, string> = {};
    if (vlabId) {
      headers['virtual-lab-id'] = vlabId;
    }
    if (projectId) {
      headers['project-id'] = projectId;
    }

    try {
      const url = `${entitycoreUrl.replace(/\/$/, '')}/ion-channel-recording/${input.ion_channel_recording_id}`;

      // Use ky's built-in JSON parsing and error handling
      const data = await httpClient
        .get(url, {
          headers,
        })
        .json<any>();

      // Add url_link to the response
      data.url_link = `${entityFrontendUrl}/${data.id}`;

      // Validate response with Zod schema
      const validated = zIonChannelRecordingRead.parse(data);
      return validated;
    } catch (error) {
      if (error instanceof HTTPError) {
        const { status, statusText } = error.response;
        let responseBody = '';
        try {
          responseBody = await error.response.text();
        } catch {
          // Ignore if we can't read the body
        }
        throw new Error(
          `The ion-channel-recording endpoint returned a non 200 response code. Error: ${status} ${statusText}${responseBody ? ': ' + responseBody : ''}`
        );
      }
      throw error;
    }
  }

  /**
   * Static health check method (classmethod equivalent)
   *
   * @param contextVariables - Context variables with API configuration
   * @returns True if the service is online
   */
  static async isOnline(contextVariables: EntitycoreContextVariables): Promise<boolean> {
    try {
      const { entitycoreUrl, httpClient } = contextVariables;
      const healthUrl = `${entitycoreUrl.replace(/\/$/, '')}/health`;

      await httpClient.get(healthUrl);
      return true;
    } catch {
      return false;
    }
  }
}
