/**
 * Ion Channel GetAll Tool
 *
 * Translated from backend/src/neuroagent/tools/entitycore_ionchannel_getall.py
 *
 * Searches a neuroscience based knowledge graph to retrieve ion-channels.
 */

import { z } from 'zod';

import { BaseTool, type EntitycoreContextVariables } from '../base-tool';
import {
  zReadManyIonChannelGetData,
  zListResponseIonChannelRead,
} from '../autogenerated_types/entitycore/zod.gen';

/**
 * Input schema for Ion Channel GetAll tool
 *
 * Extends the autogenerated query schema with custom overrides:
 * - Restricts page_size to 1-10 (default 5) instead of default 100
 *
 * Equivalent to Python's IonChannelGetAllInput which extends
 * ReadManyIonChannelGetParametersQuery
 */
const IonChannelGetAllInputSchema = zReadManyIonChannelGetData.shape.query
  .unwrap() // Remove optional wrapper
  .extend({
    // Override page_size with stricter constraints
    page_size: z
      .number()
      .int()
      .gte(1)
      .lte(10)
      .default(5)
      .describe('Number of items per page (1-10)'),
  });

/**
 * Ion Channel GetAll Tool
 *
 * Searches and retrieves ion-channels from the EntityCore knowledge graph.
 * Supports filtering by various criteria including label, gene, and metadata.
 */
export class IonChannelGetAllTool extends BaseTool<
  typeof IonChannelGetAllInputSchema,
  EntitycoreContextVariables
> {
  // Static properties (tool metadata)
  static readonly toolName = 'entitycore-ionchannel-getall';
  static readonly toolNameFrontend = 'Get All Ion Channels';
  static readonly toolDescription = `Searches a neuroscience based knowledge graph to retrieve ion-channels.
The output is a list of ion-channels, containing:
- The ion channel ID and basic identifiers
- Core ion channel information and properties
- Status and state information
- Associated metadata and relationships
- Creation and modification timestamps`;
  static readonly toolDescriptionFrontend = `Search and retrieve ion-channels. Use this tool to:
• Find ion-channels by various criteria
• Access detailed ion-channel data

Specify optional criteria to find relevant ion-channels.`;
  static readonly toolUtterances: string[] = [];
  static readonly toolHil = false;

  override contextVariables: EntitycoreContextVariables;
  override inputSchema = IonChannelGetAllInputSchema;

  constructor(contextVariables: EntitycoreContextVariables) {
    super();
    this.contextVariables = contextVariables;
  }

  /**
   * Execute the ion-channel search
   *
   * @param input - Validated search parameters
   * @returns List of ion-channels with pagination
   */
  async execute(
    input: z.infer<typeof IonChannelGetAllInputSchema>
  ): Promise<z.infer<typeof zListResponseIonChannelRead>> {
    const { entitycoreUrl, vlabId, projectId, httpClient } = this.contextVariables;

    // Prepare query parameters using URLSearchParams
    const searchParams = new URLSearchParams();
    Object.entries(input).forEach(([key, value]) => {
      if (value !== undefined) {
        if (Array.isArray(value)) {
          value.forEach((v) => searchParams.append(key, String(v)));
        } else {
          searchParams.set(key, String(value));
        }
      }
    });

    // Prepare headers
    const headers: Record<string, string> = {};
    if (vlabId) {
      headers['virtual-lab-id'] = vlabId;
    }
    if (projectId) {
      headers['project-id'] = projectId;
    }

    try {
      const url = `${entitycoreUrl.replace(/\/$/, '')}/ion-channel`;

      // Use ky's built-in JSON parsing and error handling
      const data = await httpClient
        .get(url, {
          searchParams,
          headers,
        })
        .json();

      // Validate response with Zod schema
      const validated = zListResponseIonChannelRead.parse(data);
      return validated;
    } catch (error: any) {
      throw new Error(
        `The ion-channel endpoint returned an error: ${error.message || JSON.stringify(error)}`
      );
    }
  }

  /**
   * Static health check method (classmethod equivalent)
   *
   * @param contextVariables - Context variables with API configuration
   * @returns True if the service is online
   */
  static async isOnline(contextVariables: EntitycoreContextVariables): Promise<boolean> {
    try {
      const { entitycoreUrl, httpClient } = contextVariables;
      const healthUrl = `${entitycoreUrl.replace(/\/$/, '')}/health`;

      await httpClient.get(healthUrl);
      return true;
    } catch {
      return false;
    }
  }
}
