/**
 * Ion Channel GetOne Tool
 *
 * Translated from backend/src/neuroagent/tools/entitycore_ionchannel_getone.py
 *
 * Retrieves detailed information about a specific ion-channel from the knowledge graph.
 */

import { z } from 'zod';
import { HTTPError } from 'ky';

import { BaseTool, type EntitycoreContextVariables } from '../base-tool';
import { zIonChannelRead } from '../autogenerated_types/entitycore/zod.gen';

/**
 * Input schema for Ion Channel GetOne tool
 *
 * Requires the UUID of the ion-channel to retrieve.
 * Equivalent to Python's IonChannelGetOneInput
 */
const IonChannelGetOneInputSchema = z.object({
  ion_channel_id: z.string().uuid().describe('ID of the ion-channel of interest in UUID format.'),
});

/**
 * Ion Channel GetOne Tool
 *
 * Retrieves detailed information about a specific ion-channel from the EntityCore knowledge graph.
 */
export class IonChannelGetOneTool extends BaseTool<
  typeof IonChannelGetOneInputSchema,
  EntitycoreContextVariables
> {
  // Static properties (tool metadata)
  static readonly toolName = 'entitycore-ionchannel-getone';
  static readonly toolNameFrontend = 'Get One Ion Channel';
  static readonly toolDescription = `Retrieves detailed information about a specific ion-channel from the knowledge graph.
Requires a 'ion_channel_id' which is the ID of the ion-channel of interest as registered in the knowledge graph.
The output contains detailed information about the ion-channel, including:
- The ion channel ID and basic identifiers
- Core ion channel information and properties
- Status and state information
- Associated metadata and relationships
- Creation and modification timestamps
- Creation and update dates`;
  static readonly toolDescriptionFrontend = `Get detailed information about a specific ion-channel. Use this tool to:
• View complete ion-channel details
• Access detailed ion-channel information
• Get creation and update information

Specify the ion-channel ID to retrieve its full details.`;
  static readonly toolUtterances: string[] = [];

  override contextVariables: EntitycoreContextVariables;
  override inputSchema = IonChannelGetOneInputSchema;

  constructor(contextVariables: EntitycoreContextVariables) {
    super();
    this.contextVariables = contextVariables;
  }

  /**
   * Execute the ion-channel retrieval
   *
   * @param input - Validated input containing ion_channel_id
   * @returns Detailed ion-channel information
   */
  async execute(
    input: z.infer<typeof IonChannelGetOneInputSchema>
  ): Promise<z.infer<typeof zIonChannelRead>> {
    const { entitycoreUrl, vlabId, projectId, httpClient } = this.contextVariables;

    // Prepare headers
    const headers: Record<string, string> = {};
    if (vlabId) {
      headers['virtual-lab-id'] = vlabId;
    }
    if (projectId) {
      headers['project-id'] = projectId;
    }

    try {
      const url = `${entitycoreUrl.replace(/\/$/, '')}/ion-channel/${input.ion_channel_id}`;

      // Use ky's built-in JSON parsing and error handling
      const data = await httpClient
        .get(url, {
          headers,
        })
        .json();

      // Validate response with Zod schema
      const validated = zIonChannelRead.parse(data);
      return validated;
    } catch (error) {
      if (error instanceof HTTPError) {
        const { status, statusText } = error.response;
        let responseBody = '';
        try {
          responseBody = await error.response.text();
        } catch {
          // Ignore if we can't read the body
        }
        throw new Error(
          `The ion-channel endpoint returned a non 200 response code. Error: ${status} ${statusText}${responseBody ? ': ' + responseBody : ''}`
        );
      }
      throw error;
    }
  }

  /**
   * Static health check method (classmethod equivalent)
   *
   * @param contextVariables - Context variables with API configuration
   * @returns True if the service is online
   */
  static async isOnline(contextVariables: EntitycoreContextVariables): Promise<boolean> {
    try {
      const { entitycoreUrl, httpClient } = contextVariables;
      const healthUrl = `${entitycoreUrl.replace(/\/$/, '')}/health`;

      await httpClient.get(healthUrl);
      return true;
    } catch {
      return false;
    }
  }
}
