/**
 * Measurement Annotation GetAll Tool
 *
 * Translated from backend/src/neuroagent/tools/entitycore_measurementannotation_getall.py
 *
 * Searches the entitycore database to retrieve measurement annotations.
 */

import { z } from 'zod';

import { BaseTool, type EntitycoreContextVariables } from '../base-tool';
import {
  zReadManyMeasurementAnnotationGetData,
  zListResponseMeasurementAnnotationRead,
} from '../autogenerated_types/entitycore.ts/zod.gen';

/**
 * Input schema for Measurement Annotation GetAll tool
 *
 * Extends the autogenerated query schema with custom overrides:
 * - Restricts page_size to 1-10 (default 5) instead of default 100
 * - Adds within_brain_region_brain_region_id for brain region filtering
 * - Adds within_brain_region_direction for hierarchy traversal control
 *
 * Equivalent to Python's MeasurementAnnotationGetAllInput which extends
 * EntitycoreExcludeBRParams and ReadManyMeasurementAnnotationGetParametersQuery
 */
const MeasurementAnnotationGetAllInputSchema = zReadManyMeasurementAnnotationGetData.shape.query
  .unwrap() // Remove optional wrapper
  .extend({
    // Override page_size with stricter constraints
    page_size: z
      .number()
      .int()
      .gte(1)
      .lte(10)
      .default(5)
      .describe('Number of items per page (1-10)'),

    // Add brain region filtering (from EntitycoreExcludeBRParams pattern)
    within_brain_region_brain_region_id: z
      .string()
      .uuid()
      .optional()
      .describe('ID of the brain region of interest in UUID format.'),

    // Add direction control for brain region hierarchy traversal
    within_brain_region_direction: z
      .enum(['ascendants', 'descendants', 'ascendants_and_descendants'])
      .default('ascendants_and_descendants')
      .describe(
        'Controls whether to search in parent regions (ascendants), child regions (descendants), or both when filtering by brain region.'
      ),
  });

/**
 * Measurement Annotation GetAll Tool
 *
 * Searches and retrieves measurement annotations from the EntityCore knowledge graph.
 * Supports filtering by brain region, entity type, measurement kinds, and various other criteria.
 */
export class MeasurementAnnotationGetAllTool extends BaseTool<
  typeof MeasurementAnnotationGetAllInputSchema,
  EntitycoreContextVariables
> {
  // Static properties (tool metadata)
  static readonly toolName = 'entitycore-measurementannotation-getall';
  static readonly toolNameFrontend = 'Get All Measurement Annotations';
  static readonly toolDescription = `Searches the entitycore database to retrieve measurement annotations.
The output is a list of measurement annotations, containing:
- The measurement annotation ID
- The creation date
- The update date
- The entity ID
- The entity type
- Any additional metadata

We explicitly exclude the measurement kinds but you can access them using the Get One Measurement Annotation tool.`;
  static readonly toolDescriptionFrontend = `Search and retrieve measurement annotations. Use this tool to:
• Find annotations in specific brain regions
• Filter by entity type
• Access basic annotation data

For detailed measurement kinds information, use the Get One Measurement Annotation tool.
Specify brain region and optional criteria to find relevant annotations.`;
  static readonly toolUtterances = [
    'Find measurement annotations',
    'Show me available measurement annotations',
    'What measurement annotations are there?',
  ];
  static readonly toolHil = false;

  override contextVariables: EntitycoreContextVariables;
  override inputSchema = MeasurementAnnotationGetAllInputSchema;

  constructor(contextVariables: EntitycoreContextVariables) {
    super();
    this.contextVariables = contextVariables;
  }

  /**
   * Execute the measurement annotation search
   *
   * @param input - Validated search parameters
   * @returns List of measurement annotations with pagination
   */
  async execute(
    input: z.infer<typeof MeasurementAnnotationGetAllInputSchema>
  ): Promise<z.infer<typeof zListResponseMeasurementAnnotationRead>> {
    const { entitycoreUrl, vlabId, projectId, httpClient } = this.contextVariables;

    // Prepare query parameters
    const queryParams: Record<string, any> = {};

    // Extract within_brain_region_brain_region_id and within_brain_region_direction for special handling
    const { within_brain_region_brain_region_id, within_brain_region_direction, ...restInput } = input;

    // Copy all other input parameters (excluding defaults to match Python behavior)
    Object.entries(restInput).forEach(([key, value]) => {
      if (value !== undefined) {
        queryParams[key] = value;
      }
    });

    // Always include page_size (matches Python: query_params["page_size"] = self.input_schema.page_size)
    queryParams['page_size'] = input.page_size ?? 5;

    // Prepare headers
    const headers: Record<string, string> = {};
    if (vlabId) {
      headers['virtual-lab-id'] = vlabId;
    }
    if (projectId) {
      headers['project-id'] = projectId;
    }

    try {
      // Retrieve the hierarchy_id from brain_region_id if provided
      if (within_brain_region_brain_region_id) {
        const brainRegionUrl = `${entitycoreUrl.replace(/\/$/, '')}/brain-region/${within_brain_region_brain_region_id}`;

        const brainRegionResponse = await httpClient.get(brainRegionUrl, { headers }).json<any>();

        if (!brainRegionResponse || !brainRegionResponse.hierarchy_id) {
          throw new Error('The Brain Region endpoint returned invalid data.');
        }

        queryParams['within_brain_region_hierarchy_id'] = brainRegionResponse.hierarchy_id;

        // Only add within_brain_region_direction when hierarchy_id is present
        // (matches Python: query_params["within_brain_region_direction"] = self.input_schema.within_brain_region_direction)
        queryParams['within_brain_region_direction'] = within_brain_region_direction ?? 'ascendants_and_descendants';
      }

      // Prepare search params
      const searchParams = new URLSearchParams();
      Object.entries(queryParams).forEach(([key, value]) => {
        if (value !== undefined) {
          if (Array.isArray(value)) {
            value.forEach((v) => searchParams.append(key, String(v)));
          } else {
            searchParams.set(key, String(value));
          }
        }
      });

      const url = `${entitycoreUrl.replace(/\/$/, '')}/measurement-annotation`;

      // Use ky's built-in JSON parsing and error handling
      const data = await httpClient
        .get(url, {
          searchParams,
          headers,
        })
        .json<any>();

      // Set measurement_kinds to empty list for each annotation
      // This matches the Python implementation's behavior
      if (data.data && Array.isArray(data.data)) {
        for (const annotation of data.data) {
          annotation.measurement_kinds = [];
        }
      }

      // Validate response with Zod schema
      const validated = zListResponseMeasurementAnnotationRead.parse(data);
      return validated;
    } catch (error: any) {
      // Handle brain region endpoint errors
      if (error.message?.includes('Brain Region')) {
        throw error;
      }

      // Handle measurement annotation endpoint errors
      throw new Error(
        `The measurement annotation endpoint returned an error: ${error.message || JSON.stringify(error)}`
      );
    }
  }

  /**
   * Static health check method (classmethod equivalent)
   *
   * @param contextVariables - Context variables with API configuration
   * @returns True if the service is online
   */
  static async isOnline(contextVariables: EntitycoreContextVariables): Promise<boolean> {
    try {
      const { entitycoreUrl, httpClient } = contextVariables;
      const healthUrl = `${entitycoreUrl.replace(/\/$/, '')}/health`;

      await httpClient.get(healthUrl);
      return true;
    } catch {
      return false;
    }
  }
}
