/**
 * Organization GetAll Tool
 *
 * Translated from backend/src/neuroagent/tools/entitycore_organization_getall.py
 *
 * Searches a neuroscience based knowledge graph to retrieve organizations.
 */

import { z } from 'zod';
import { HTTPError } from 'ky';

import { BaseTool, type EntitycoreContextVariables } from '../base-tool';
import {
  zReadManyOrganizationGetData,
  zListResponseOrganizationRead,
} from '../autogenerated_types/entitycore/zod.gen';

/**
 * Input schema for Organization GetAll tool
 *
 * Extends the autogenerated query schema with custom overrides:
 * - Restricts page_size to 1-10 (default 5) instead of default 100
 *
 * Note: Organizations don't have brain_region parameters, so no EntitycoreExcludeBRParams needed
 */
const OrganizationGetAllInputSchema = zReadManyOrganizationGetData.shape.query
  .unwrap() // Remove optional wrapper
  .extend({
    // Override page_size with stricter constraints
    page_size: z
      .number()
      .int()
      .gte(1)
      .lte(10)
      .default(5)
      .describe('Number of items per page (1-10)'),
  });

/**
 * Organization GetAll Tool
 *
 * Searches and retrieves organizations from the EntityCore knowledge graph.
 * Supports filtering by name, ID, type, and creator information.
 */
export class OrganizationGetAllTool extends BaseTool<
  typeof OrganizationGetAllInputSchema,
  EntitycoreContextVariables
> {
  // Static properties (tool metadata)
  static readonly toolName = 'entitycore-organization-getall';
  static readonly toolNameFrontend = 'Get All Organizations';
  static readonly toolDescription = `Searches a neuroscience based knowledge graph to retrieve organizations.
The output is a list of organizations, containing:
- The organization ID
- The organization's preferred label
- The organization's alternative name`;
  static readonly toolDescriptionFrontend = `Search and retrieve organizations. Use this tool to:
• Find organizations by name
• Access detailed organization data

Specify optional criteria to find relevant organizations.`;
  static readonly toolUtterances = [
    'Find organizations',
    'Show me available organizations',
    'What organizations are there?',
  ];

  override contextVariables: EntitycoreContextVariables;
  override inputSchema = OrganizationGetAllInputSchema;

  constructor(contextVariables: EntitycoreContextVariables) {
    super();
    this.contextVariables = contextVariables;
  }

  /**
   * Execute the organization search
   *
   * @param input - Validated search parameters
   * @returns List of organizations with pagination
   */
  async execute(
    input: z.infer<typeof OrganizationGetAllInputSchema>
  ): Promise<z.infer<typeof zListResponseOrganizationRead>> {
    const { entitycoreUrl, vlabId, projectId, httpClient } = this.contextVariables;

    // Prepare query parameters
    const queryParams: Record<string, string | string[]> = {};

    // Add all parameters to query
    Object.entries(input).forEach(([key, value]) => {
      if (value !== undefined) {
        queryParams[key] = Array.isArray(value) ? value.map(String) : String(value);
      }
    });

    // Prepare headers
    const headers: Record<string, string> = {};
    if (vlabId) {
      headers['virtual-lab-id'] = vlabId;
    }
    if (projectId) {
      headers['project-id'] = projectId;
    }

    try {
      const url = `${entitycoreUrl.replace(/\/$/, '')}/organization`;

      // Use ky's built-in JSON parsing and error handling
      const data = await httpClient
        .get(url, {
          searchParams: queryParams as any,
          headers,
        })
        .json<any>();

      // Validate response with Zod schema
      const validated = zListResponseOrganizationRead.parse(data);
      return validated;
    } catch (error) {
      if (error instanceof HTTPError) {
        const { status, statusText } = error.response;
        let responseBody = '';
        try {
          responseBody = await error.response.text();
        } catch {
          // Ignore if we can't read the body
        }
        throw new Error(
          `The organization endpoint returned a non 200 response code. Error: ${status} ${statusText}${responseBody ? ': ' + responseBody : ''}`
        );
      }
      throw error;
    }
  }

  /**
   * Static health check method (classmethod equivalent)
   *
   * @param contextVariables - Context variables with API configuration
   * @returns True if the service is online
   */
  static async isOnline(contextVariables: EntitycoreContextVariables): Promise<boolean> {
    try {
      const { entitycoreUrl, httpClient } = contextVariables;
      const healthUrl = `${entitycoreUrl.replace(/\/$/, '')}/health`;

      await httpClient.get(healthUrl);
      return true;
    } catch {
      return false;
    }
  }
}
