/**
 * Person GetOne Tool
 *
 * Translated from backend/src/neuroagent/tools/entitycore_person_getone.py
 *
 * Retrieves detailed information about a specific person from the knowledge graph.
 */

import { z } from 'zod';
import { HTTPError } from 'ky';

import { BaseTool, type EntitycoreContextVariables } from '../base-tool';
import { zPersonRead } from '../autogenerated_types/entitycore/zod.gen';

/**
 * Input schema for Person GetOne tool
 *
 * Equivalent to Python's PersonGetOneInput
 */
const PersonGetOneInputSchema = z.object({
  person_id: z.string().uuid().describe('ID of the person of interest in UUID format.'),
});

/**
 * Person GetOne Tool
 *
 * Retrieves detailed information about a specific person from the EntityCore knowledge graph.
 */
export class PersonGetOneTool extends BaseTool<
  typeof PersonGetOneInputSchema,
  EntitycoreContextVariables
> {
  // Static properties (tool metadata)
  static readonly toolName = 'entitycore-person-getone';
  static readonly toolNameFrontend = 'Get One Person';
  static readonly toolDescription = `Retrieves detailed information about a specific person from the knowledge graph.
Requires a 'person_id' which is the ID of the person of interest as registered in the knowledge graph.
The output contains detailed information about the person, including:
- The person ID
- The person's given name
- The person's family name
- The person's preferred label
- Creation and update dates`;
  static readonly toolDescriptionFrontend = `Get detailed information about a specific person. Use this tool to:
• View complete person details
• Access person names and labels
• Get creation and update information

Specify the person ID to retrieve their full details.`;
  static readonly toolUtterances = [
    'Get details for this person',
    'Show me information about this person',
    'What are the properties of this person?',
  ];
  static readonly toolHil = false;

  override contextVariables: EntitycoreContextVariables;
  override inputSchema = PersonGetOneInputSchema;

  constructor(contextVariables: EntitycoreContextVariables) {
    super();
    this.contextVariables = contextVariables;
  }

  /**
   * Execute the person retrieval
   *
   * @param input - Validated input with person_id
   * @returns Detailed person information
   */
  async execute(
    input: z.infer<typeof PersonGetOneInputSchema>
  ): Promise<z.infer<typeof zPersonRead>> {
    const { entitycoreUrl, vlabId, projectId, httpClient } = this.contextVariables;

    // Prepare headers
    const headers: Record<string, string> = {};
    if (vlabId) {
      headers['virtual-lab-id'] = vlabId;
    }
    if (projectId) {
      headers['project-id'] = projectId;
    }

    try {
      const url = `${entitycoreUrl.replace(/\/$/, '')}/person/${input.person_id}`;

      // Use ky's built-in JSON parsing and error handling
      const data = await httpClient
        .get(url, {
          headers,
        })
        .json<any>();

      // Validate response with Zod schema
      const validated = zPersonRead.parse(data);
      return validated;
    } catch (error) {
      if (error instanceof HTTPError) {
        const { status, statusText } = error.response;
        let responseBody = '';
        try {
          responseBody = await error.response.text();
        } catch {
          // Ignore if we can't read the body
        }
        throw new Error(
          `The person endpoint returned a non 200 response code. Error: ${status} ${statusText}${responseBody ? ': ' + responseBody : ''}`
        );
      }
      throw error;
    }
  }

  /**
   * Static health check method (classmethod equivalent)
   *
   * @param contextVariables - Context variables with API configuration
   * @returns True if the service is online
   */
  static async isOnline(contextVariables: EntitycoreContextVariables): Promise<boolean> {
    try {
      const { entitycoreUrl, httpClient } = contextVariables;
      const healthUrl = `${entitycoreUrl.replace(/\/$/, '')}/health`;

      await httpClient.get(healthUrl);
      return true;
    } catch {
      return false;
    }
  }
}
