/**
 * Single Neuron Synaptome GetOne Tool
 *
 * Translated from backend/src/neuroagent/tools/entitycore_singleneuronsynaptome_getone.py
 *
 * Retrieves detailed information about a specific single-neuron-synaptome from the knowledge graph.
 */

import { z } from 'zod';

import { BaseTool, type EntitycoreContextVariables } from '../base-tool';
import {
  zReadOneSingleNeuronSynaptomeIdGetData,
  zSingleNeuronSynaptomeRead,
} from '../autogenerated_types/entitycore.ts/zod.gen';

/**
 * Input schema for Single Neuron Synaptome GetOne tool
 *
 * Requires a single_neuron_synaptome_id to retrieve specific synaptome details.
 * Equivalent to Python's SingleNeuronSynaptomeGetOneInput
 */
const SingleNeuronSynaptomeGetOneInputSchema = z.object({
  single_neuron_synaptome_id: z
    .string()
    .uuid()
    .describe('ID of the single-neuron-synaptome of interest in UUID format.'),
});

/**
 * Single Neuron Synaptome GetOne Tool
 *
 * Retrieves detailed information about a specific single-neuron-synaptome.
 */
export class SingleNeuronSynaptomeGetOneTool extends BaseTool<
  typeof SingleNeuronSynaptomeGetOneInputSchema,
  EntitycoreContextVariables
> {
  // Static properties (tool metadata)
  static readonly toolName = 'entitycore-singleneuronsynaptome-getone';
  static readonly toolNameFrontend = 'Get One Single Neuron Synaptome';
  static readonly toolDescription = `Retrieves detailed information about a specific single-neuron-synaptome from the knowledge graph.
Requires a 'single_neuron_synaptome_id' which is the ID of the single-neuron-synaptome of interest as registered in the knowledge graph.
The output contains detailed information about the single-neuron-synaptome, including:
- The single neuron synaptome ID and basic identifiers
- Core single neuron synaptome information and properties
- Status and state information
- Associated metadata and relationships
- Creation and modification timestamps
- Creation and update dates`;
  static readonly toolDescriptionFrontend = `Get detailed information about a specific single-neuron-synaptome. Use this tool to:
• View complete single-neuron-synaptome details
• Access detailed single-neuron-synaptome information
• Get creation and update information

Specify the single-neuron-synaptome ID to retrieve its full details.`;
  static readonly toolUtterances = [
    'Get details for this single neuron synaptome',
    'Show me information about this single neuron synaptome',
    'What are the properties of this single neuron synaptome?',
  ];
  static readonly toolHil = false;

  override contextVariables: EntitycoreContextVariables;
  override inputSchema = SingleNeuronSynaptomeGetOneInputSchema;

  constructor(contextVariables: EntitycoreContextVariables) {
    super();
    this.contextVariables = contextVariables;
  }

  /**
   * Execute the single-neuron-synaptome retrieval
   *
   * @param input - Validated input with single_neuron_synaptome_id
   * @returns Detailed single-neuron-synaptome information
   */
  async execute(
    input: z.infer<typeof SingleNeuronSynaptomeGetOneInputSchema>
  ): Promise<z.infer<typeof zSingleNeuronSynaptomeRead>> {
    const { entitycoreUrl, vlabId, projectId, httpClient, entityFrontendUrl } =
      this.contextVariables;

    // Prepare headers
    const headers: Record<string, string> = {};
    if (vlabId) {
      headers['virtual-lab-id'] = vlabId;
    }
    if (projectId) {
      headers['project-id'] = projectId;
    }

    try {
      const url = `${entitycoreUrl.replace(/\/$/, '')}/single-neuron-synaptome/${input.single_neuron_synaptome_id}`;

      // Use ky's built-in JSON parsing and error handling
      const data = await httpClient
        .get(url, {
          headers,
        })
        .json<any>();

      // Add the link to website (matching Python behavior)
      data.url_link = `${entityFrontendUrl}/${data.id}`;

      // Validate response with Zod schema
      const validated = zSingleNeuronSynaptomeRead.parse(data);
      return validated;
    } catch (error: any) {
      throw new Error(
        `The single-neuron-synaptome endpoint returned an error: ${error.message || JSON.stringify(error)}`
      );
    }
  }

  /**
   * Static health check method (classmethod equivalent)
   *
   * @param contextVariables - Context variables with API configuration
   * @returns True if the service is online
   */
  static async isOnline(contextVariables: EntitycoreContextVariables): Promise<boolean> {
    try {
      const { entitycoreUrl, httpClient } = contextVariables;
      const healthUrl = `${entitycoreUrl.replace(/\/$/, '')}/health`;

      await httpClient.get(healthUrl);
      return true;
    } catch {
      return false;
    }
  }
}
