/**
 * Species GetOne Tool
 *
 * Translated from backend/src/neuroagent/tools/entitycore_species_getone.py
 *
 * Retrieves detailed information about a specific species from the knowledge graph.
 */

import { z } from 'zod';

import { BaseTool, type EntitycoreContextVariables } from '../base-tool';
import { zSpeciesRead } from '../autogenerated_types/entitycore/zod.gen';

/**
 * Input schema for Species GetOne tool
 *
 * Requires a species_id to retrieve detailed information about a specific species.
 */
const SpeciesGetOneInputSchema = z.object({
  species_id: z.string().uuid().describe('ID of the species of interest in UUID format.'),
});

/**
 * Species GetOne Tool
 *
 * Retrieves detailed information about a specific species from the EntityCore knowledge graph.
 */
export class SpeciesGetOneTool extends BaseTool<
  typeof SpeciesGetOneInputSchema,
  EntitycoreContextVariables
> {
  // Static properties (tool metadata)
  static readonly toolName = 'entitycore-species-getone';
  static readonly toolNameFrontend = 'Get One Species';
  static readonly toolDescription = `Retrieves detailed information about a specific species from the knowledge graph.
Requires a 'species_id' which is the ID of the species of interest as registered in the knowledge graph.
The output contains detailed information about the species, including:
- The species ID
- The species name
- The species taxonomy ID
- Creation and update dates`;
  static readonly toolDescriptionFrontend = `Get detailed information about a specific species. Use this tool to:
• View complete species details
• Access species name and taxonomy ID
• Get creation and update information

Specify the species ID to retrieve its full details.`;
  static readonly toolUtterances = [
    'Get details for this species',
    'Show me information about this species',
    'What are the properties of this species?',
  ];
  static readonly toolHil = false;

  override contextVariables: EntitycoreContextVariables;
  override inputSchema = SpeciesGetOneInputSchema;

  constructor(contextVariables: EntitycoreContextVariables) {
    super();
    this.contextVariables = contextVariables;
  }

  /**
   * Execute the species retrieval
   *
   * @param input - Validated input with species_id
   * @returns Detailed species information
   */
  async execute(
    input: z.infer<typeof SpeciesGetOneInputSchema>
  ): Promise<z.infer<typeof zSpeciesRead>> {
    const { entitycoreUrl, vlabId, projectId, httpClient } = this.contextVariables;

    // Prepare headers
    const headers: Record<string, string> = {};
    if (vlabId) {
      headers['virtual-lab-id'] = vlabId;
    }
    if (projectId) {
      headers['project-id'] = projectId;
    }

    try {
      const url = `${entitycoreUrl.replace(/\/$/, '')}/species/${input.species_id}`;

      // Use ky's built-in JSON parsing and error handling
      const data = await httpClient
        .get(url, {
          headers,
        })
        .json<any>();

      // Validate response with Zod schema
      const validated = zSpeciesRead.parse(data);
      return validated;
    } catch (error: any) {
      throw new Error(
        `The species endpoint returned an error: ${error.message || JSON.stringify(error)}`
      );
    }
  }

  /**
   * Static health check method (classmethod equivalent)
   *
   * @param contextVariables - Context variables with API configuration
   * @returns True if the service is online
   */
  static async isOnline(contextVariables: EntitycoreContextVariables): Promise<boolean> {
    try {
      const { entitycoreUrl, httpClient } = contextVariables;
      const healthUrl = `${entitycoreUrl.replace(/\/$/, '')}/health`;

      await httpClient.get(healthUrl);
      return true;
    } catch {
      return false;
    }
  }
}
