/**
 * Subject GetAll Tool
 *
 * Translated from backend/src/neuroagent/tools/entitycore_subject_getall.py
 *
 * Searches a neuroscience based knowledge graph to retrieve subjects.
 */

import { z } from 'zod';
import { HTTPError } from 'ky';

import { BaseTool, type EntitycoreContextVariables } from '../base-tool';
import {
  zReadManySubjectGetData,
  zListResponseSubjectRead,
} from '../autogenerated_types/entitycore/zod.gen';

/**
 * Input schema for Subject GetAll tool
 *
 * Extends the autogenerated query schema with custom overrides:
 * - Restricts page_size to 1-10 (default 5) instead of default 100
 *
 * Equivalent to Python's SubjectGetAllInput which extends
 * ReadManySubjectGetParametersQuery
 */
const SubjectGetAllInputSchema = zReadManySubjectGetData.shape.query
  .unwrap() // Remove optional wrapper
  .extend({
    // Override page_size with stricter constraints
    page_size: z
      .number()
      .int()
      .gte(1)
      .lte(10)
      .default(5)
      .describe('Number of items per page (1-10)'),
  });

/**
 * Subject GetAll Tool
 *
 * Searches and retrieves subjects from the EntityCore knowledge graph.
 * Supports filtering by species, strain, age, sex, and various other criteria.
 */
export class SubjectGetAllTool extends BaseTool<
  typeof SubjectGetAllInputSchema,
  EntitycoreContextVariables
> {
  // Static properties (tool metadata)
  static readonly toolName = 'entitycore-subject-getall';
  static readonly toolNameFrontend = 'Get All Subjects';
  static readonly toolDescription = `Searches a neuroscience based knowledge graph to retrieve subjects.
The output is a list of subjects, containing:
- The subject ID
- The subject name
- The subject description
- The subject sex
- The subject weight
- The subject age information
- The subject species`;
  static readonly toolDescriptionFrontend = `Search and retrieve subjects. Use this tool to:
• Find subjects by name
• Access detailed subject data
• Filter subjects by various criteria

Specify optional criteria to find relevant subjects.`;
  static readonly toolUtterances = [
    'Find subjects',
    'Show me available subjects',
    'What subjects are there?',
  ];
  static readonly toolHil = false;

  override contextVariables: EntitycoreContextVariables;
  override inputSchema = SubjectGetAllInputSchema;

  constructor(contextVariables: EntitycoreContextVariables) {
    super();
    this.contextVariables = contextVariables;
  }

  /**
   * Execute the subject search
   *
   * @param input - Validated search parameters
   * @returns List of subjects with pagination
   */
  async execute(
    input: z.infer<typeof SubjectGetAllInputSchema>
  ): Promise<z.infer<typeof zListResponseSubjectRead>> {
    const { entitycoreUrl, vlabId, projectId, httpClient } = this.contextVariables;

    // Prepare query parameters
    const queryParams: Record<string, string | string[]> = {};

    // Add all parameters to query
    Object.entries(input).forEach(([key, value]) => {
      if (value !== undefined) {
        queryParams[key] = Array.isArray(value) ? value.map(String) : String(value);
      }
    });

    // Prepare headers
    const headers: Record<string, string> = {};
    if (vlabId) {
      headers['virtual-lab-id'] = vlabId;
    }
    if (projectId) {
      headers['project-id'] = projectId;
    }

    try {
      const url = `${entitycoreUrl.replace(/\/$/, '')}/subject`;

      // Use ky's built-in JSON parsing and error handling
      const data = await httpClient
        .get(url, {
          searchParams: queryParams as any,
          headers,
        })
        .json<any>();

      // Validate response with Zod schema
      const validated = zListResponseSubjectRead.parse(data);
      return validated;
    } catch (error) {
      if (error instanceof HTTPError) {
        const { status, statusText } = error.response;
        let responseBody = '';
        try {
          responseBody = await error.response.text();
        } catch {
          // Ignore if we can't read the body
        }
        throw new Error(
          `The subject endpoint returned a non 200 response code. Error: ${status} ${statusText}${responseBody ? ': ' + responseBody : ''}`
        );
      }
      throw error;
    }
  }

  /**
   * Static health check method (classmethod equivalent)
   *
   * @param contextVariables - Context variables with API configuration
   * @returns True if the service is online
   */
  static async isOnline(contextVariables: EntitycoreContextVariables): Promise<boolean> {
    try {
      const { entitycoreUrl, httpClient } = contextVariables;
      const healthUrl = `${entitycoreUrl.replace(/\/$/, '')}/health`;

      await httpClient.get(healthUrl);
      return true;
    } catch {
      return false;
    }
  }
}
