"""Initial migration

Revision ID: 4982d57abbab
Revises:
Create Date: 2025-01-21 08:58:17.515181

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4982d57abbab"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "threads",
        sa.Column("thread_id", sa.String(), nullable=False),
        sa.Column("vlab_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("creation_date", sa.DateTime(), nullable=False),
        sa.Column("update_date", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("thread_id", name=op.f("pk_threads")),
    )
    op.create_table(
        "messages",
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("creation_date", sa.DateTime(), nullable=False),
        sa.Column(
            "role", sa.Enum("USER", "ASSISTANT", "TOOL", name="role"), nullable=False
        ),
        sa.Column("has_content", sa.Boolean(), nullable=False),
        sa.Column("has_tool_calls", sa.Boolean(), nullable=False),
        sa.Column("payload", sa.String(), nullable=False),
        sa.Column("thread_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.thread_id"],
            name=op.f("fk_messages_thread_id_threads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("message_id", name=op.f("pk_messages")),
    )
    op.create_table(
        "tool_calls",
        sa.Column("tool_call_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("arguments", sa.String(), nullable=False),
        sa.Column("validated", sa.Boolean(), nullable=True),
        sa.Column("message_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.message_id"],
            name=op.f("fk_tool_calls_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tool_call_id", name=op.f("pk_tool_calls")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tool_calls")
    op.drop_table("messages")
    op.drop_table("threads")
    # ### end Alembic commands ###
