"""Partial messages

Revision ID: 08a638866869
Revises: 818a9ba86187
Create Date: 2025-04-07 11:38:27.425849

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08a638866869"
down_revision: Union[str, None] = "818a9ba86187"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        # Add the column, making it nullable first to avoid conflict during addition
        batch_op.add_column(sa.Column("is_complete", sa.Boolean(), nullable=True))

    # Now that the column is added, we can safely update the values
    op.execute("""
        UPDATE messages
        SET is_complete = TRUE
        WHERE is_complete IS NULL;
    """)

    # After updating, make the column non-nullable
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.alter_column("is_complete", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_column("is_complete")

    # ### end Alembic commands ###
