"""add model column to messages

Revision ID: 52d7f4485020
Revises: 0ea274d7a584
Create Date: 2025-06-19 11:51:26.918157

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52d7f4485020"
down_revision: Union[str, None] = "0ea274d7a584"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("model", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "model")
    # ### end Alembic commands ###
