"""message content jsonb

Revision ID: 92694adcad71
Revises: cd5a73ea91db
Create Date: 2025-10-08 17:00:43.134455

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92694adcad71"
down_revision: Union[str, None] = "cd5a73ea91db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "messages",
        "content",
        existing_type=sa.VARCHAR(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        postgresql_using="content::jsonb",
    )  # Add this parameter
    op.drop_index(op.f("ix_messages_thread_entity"), table_name="messages")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_messages_thread_entity"),
        "messages",
        ["thread_id", "entity"],
        unique=False,
    )
    op.alter_column(
        "messages",
        "content",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        postgresql_using="content::text",
    )  # Add this parameter
    # ### end Alembic commands ###
