"""Introduce parent thread id

Revision ID: e5caaf5a29f0
Revises: 6d8986f38d7b
Create Date: 2026-02-26 12:52:05.229661

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5caaf5a29f0"
down_revision: Union[str, None] = "6d8986f38d7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE task ADD VALUE IF NOT EXISTS 'SUMMARY'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("complexity_estimation_message_id_fkey"),
        "complexity_estimation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("complexity_estimation_message_id_fkey"),
        "complexity_estimation",
        "messages",
        ["message_id"],
        ["message_id"],
    )
    op.drop_constraint(op.f("messages_thread_id_fkey"), "messages", type_="foreignkey")
    op.create_foreign_key(
        op.f("messages_thread_id_fkey"),
        "messages",
        "threads",
        ["thread_id"],
        ["thread_id"],
    )
    op.add_column("threads", sa.Column("parent_thread_id", sa.UUID(), nullable=True))
    op.drop_constraint(
        op.f("token_consumption_message_id_fkey"),
        "token_consumption",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("token_consumption_message_id_fkey"),
        "token_consumption",
        "messages",
        ["message_id"],
        ["message_id"],
    )
    op.drop_constraint(
        op.f("tool_calls_message_id_fkey"), "tool_calls", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("tool_calls_message_id_fkey"),
        "tool_calls",
        "messages",
        ["message_id"],
        ["message_id"],
    )
    op.drop_constraint(
        op.f("tool_selection_message_id_fkey"), "tool_selection", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("tool_selection_message_id_fkey"),
        "tool_selection",
        "messages",
        ["message_id"],
        ["message_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("ALTER TYPE task RENAME TO task_old")
    op.execute(
        "CREATE TYPE task AS ENUM('CHAT_COMPLETION', 'TOOL_SELECTION', 'CALL_WITHIN_TOOL')"
    )
    op.execute(
        "ALTER TABLE token_consumption ALTER COLUMN task TYPE task USING task::text::task"
    )
    op.execute("DROP TYPE task_old")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("tool_selection_message_id_fkey"), "tool_selection", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("tool_selection_message_id_fkey"),
        "tool_selection",
        "messages",
        ["message_id"],
        ["message_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("tool_calls_message_id_fkey"), "tool_calls", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("tool_calls_message_id_fkey"),
        "tool_calls",
        "messages",
        ["message_id"],
        ["message_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("token_consumption_message_id_fkey"),
        "token_consumption",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("token_consumption_message_id_fkey"),
        "token_consumption",
        "messages",
        ["message_id"],
        ["message_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("threads", "parent_thread_id")
    op.drop_constraint(op.f("messages_thread_id_fkey"), "messages", type_="foreignkey")
    op.create_foreign_key(
        op.f("messages_thread_id_fkey"),
        "messages",
        "threads",
        ["thread_id"],
        ["thread_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("complexity_estimation_message_id_fkey"),
        "complexity_estimation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("complexity_estimation_message_id_fkey"),
        "complexity_estimation",
        "messages",
        ["message_id"],
        ["message_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
