"""Tests Get Morpho tool."""

import json
from pathlib import Path
from uuid import uuid4

import httpx
import pytest

from neuroagent.tools import MorphologyGetAllTool
from neuroagent.tools.autogenerated_types.entitycore.models import (
    ReconstructionMorphologyRead,
)
from neuroagent.tools.entitycore_morphology_getall import (
    ListResponseReconstructionMorphologyRead,
    MorphologyGetAllInput,
    MorphologyGetAllMetadata,
)


class TestMorphologyGetAllTool:
    @pytest.mark.asyncio
    async def test_arun(self, httpx_mock):
        url = "http://fake_url"

        # Load the entitcor response
        json_path = (
            Path(__file__).resolve().parent.parent
            / "data"
            / "entitycore_morphologies_thalamus.json"
        )
        with open(json_path) as f:
            entitycore_response = json.load(f)

        random_uuid = str(uuid4())
        # Mock the entitycore API response - note that you cannot include default query parameters - e.g. (page=1)
        httpx_mock.add_response(
            url=url
            + f"/reconstruction-morphology?page_size=10&within_brain_region_hierarchy_id=e3e70682-c209-4cac-a29f-6fbed82c07cd&within_brain_region_brain_region_id={random_uuid}",
            json=entitycore_response,
        )

        tool = MorphologyGetAllTool(
            input_schema=MorphologyGetAllInput(
                brain_region_id=random_uuid,
                mtype_id=None,
                page_size=10,
                page=1,
            ),
            metadata=MorphologyGetAllMetadata(
                entitycore_url=url,
                httpx_client=httpx.AsyncClient(),
                token="fake_token",
                project_id="test_project",
                vlab_id="test_vlab",
            ),
        )

        response = await tool.arun()
        assert isinstance(response, ListResponseReconstructionMorphologyRead)
        assert len(response.data) == 3
        assert isinstance(response.data[0], ReconstructionMorphologyRead)

    @pytest.mark.asyncio
    async def test_arun_errors(
        self,
        httpx_mock,
    ):
        random_uuid = str(uuid4())
        url = "http://fake_url"

        httpx_mock.add_response(
            url=url
            + f"/reconstruction-morphology?page_size=10&within_brain_region_hierarchy_id=e3e70682-c209-4cac-a29f-6fbed82c07cd&within_brain_region_brain_region_id={random_uuid}",
            json="Not found",
            status_code=404,
        )

        tool = MorphologyGetAllTool(
            input_schema=MorphologyGetAllInput(
                brain_region_id=str(random_uuid),
                page_size=10,
                page=1,
            ),
            metadata=MorphologyGetAllMetadata(
                entitycore_url=url,
                httpx_client=httpx.AsyncClient(),
                token="fake_token",
                project_id=None,
                vlab_id=None,
            ),
        )
        with pytest.raises(ValueError) as tool_exception:
            await tool.arun()

        assert (
            tool_exception.value.args[0]
            == 'The morphology endpoint returned a non 200 response code. Error: "Not found"'
        )
