/**
 * Get One Electrical Cell Recording Thumbnail tool.
 * Translated from: backend/src/neuroagent/tools/thumbnailgen_electricalcellrecording_getone.py
 */

import { z } from 'zod';
import { HTTPError } from 'ky';
import { BaseTool } from '../base-tool';
import { ThumbnailGenerationContextVariables } from './types';
import { zGetEphysPreviewApiThumbnailGenerationCoreElectricalCellRecordingPreviewGetData } from '../autogenerated_types/thumbnail_generation/zod.gen';
import { saveToStorage } from './storage';

/**
 * Input schema for the Plot Electrical Cell Recording tool.
 * Extends the autogenerated schema, excluding asset_id (fetched internally).
 */
const PlotElectricalCellRecordingGetOneInputSchema =
  zGetEphysPreviewApiThumbnailGenerationCoreElectricalCellRecordingPreviewGetData.shape.query
    .omit({ asset_id: true })
    .extend({
      entity_id: z
        .string()
        .uuid()
        .describe('ID of the target electrical cell recording entity.'),
      dpi: z
        .number()
        .int()
        .gte(10)
        .lte(600)
        .optional()
        .describe('DPI for the generated image.'),
    });

/**
 * Output schema for the Plot Electrical Cell Recording tool.
 */
const PlotElectricalCellRecordingGetOneOutputSchema = z.object({
  storage_id: z
    .string()
    .describe('Identifier for where the generated plot is stored.'),
});

/**
 * Tool to generate a visual representation of an electrical cell recording.
 */
export class PlotElectricalCellRecordingGetOneTool extends BaseTool<
  typeof PlotElectricalCellRecordingGetOneInputSchema,
  ThumbnailGenerationContextVariables
> {
  static toolName = 'thumbnail-generation-electricalcellrecording-getone';
  static toolNameFrontend = 'Get Electrical Cell Recording Thumbnail';

  static toolDescription = `**Purpose**:
Generate a visual representation of a specified electrical cell recording.

**When to Call**:
When the user asks to plot a electrical cell recording (trace) or requests more information about it.

**Inputs**:
entity_id: ID of the target entity.

**Output**:
storage_id: Identifier for where the generated plot is stored.

**Notes**:
Do not embed or display the plot link directly in your response.`;

  static toolDescriptionFrontend = `Plot the electrical cell recording of your choice to display a thumbnail in the chat.

Use this tool to enhance the description of your target electrical cell recording by adding visuals.`;

  static toolUtterances = [
    'Create a visual representation',
    'Generate a thumbnail for this electrical cell recording',
    'Show me a visualization of this electrical cell recording',
    'Find a trace in the isocortex and plot it.',
    'Plot the following trace.',
    'Generate a thumbnail for this trace',
  ];

  override contextVariables: ThumbnailGenerationContextVariables;
  override inputSchema = PlotElectricalCellRecordingGetOneInputSchema;

  constructor(contextVariables: ThumbnailGenerationContextVariables) {
    super();
    this.contextVariables = contextVariables;
  }

  /**
   * Execute the tool to generate an electrical cell recording thumbnail.
   *
   * @param input - Tool input containing entity_id and optional dpi
   * @returns Object containing the storage_id where the plot is stored
   */
  async execute(
    input: z.infer<typeof PlotElectricalCellRecordingGetOneInputSchema>
  ): Promise<z.infer<typeof PlotElectricalCellRecordingGetOneOutputSchema>> {
    const {
      httpClient,
      entitycoreUrl,
      thumbnailGenerationUrl,
      s3Client,
      bucketName,
      userId,
      threadId,
      vlabId,
      projectId,
    } = this.contextVariables;

    // Prepare headers
    const headers: Record<string, string> = {};
    if (vlabId) {
      headers['virtual-lab-id'] = vlabId;
    }
    if (projectId) {
      headers['project-id'] = projectId;
    }

    try {
      // Retrieve the asset_id from the entity_id
      const electricalRecordingResponse = await httpClient.get(
        `${entitycoreUrl.replace(/\/$/, '')}/electrical-cell-recording/${input.entity_id}`,
        { headers }
      );

      const electricalRecording =
        (await electricalRecordingResponse.json()) as any;
      const assets = electricalRecording.assets;

      if (!assets || !Array.isArray(assets)) {
        throw new Error(
          `No assets found for electrical cell recording ${input.entity_id}`
        );
      }

      // Get the nwb asset
      const nwbAsset = assets.find(
        (asset: any) => asset.content_type === 'application/nwb'
      );

      if (!nwbAsset) {
        throw new Error(
          `No NWB asset found for the electrical cell recording ${input.entity_id}`
        );
      }

      // Prepare query parameters
      const queryParams: Record<string, string> = {
        entity_id: input.entity_id,
        asset_id: nwbAsset.id,
      };

      if (input.dpi !== undefined) {
        queryParams['dpi'] = input.dpi.toString();
      }

      // Request thumbnail generation
      const thumbnailResponse = await httpClient.get(
        `${thumbnailGenerationUrl.replace(/\/$/, '')}/core/electrical-cell-recording/preview`,
        {
          headers,
          searchParams: queryParams,
        }
      );

      // Get the image content as buffer
      const imageBuffer = await thumbnailResponse.arrayBuffer();

      // Save to storage
      const storageId = await saveToStorage(
        s3Client,
        bucketName,
        userId,
        'image/png',
        'image',
        Buffer.from(imageBuffer),
        threadId
      );

      return { storage_id: storageId };
    } catch (error) {
      if (error instanceof HTTPError) {
        const errorText = await error.response.text();
        throw new Error(
          `The Electrical Cell Recording endpoint returned a non-200 response code. Error: ${errorText}`
        );
      }
      throw error;
    }
  }

  /**
   * Check if the thumbnail generation service is online.
   *
   * @param contextVariables - Context variables containing httpClient and thumbnailGenerationUrl
   * @returns True if the service is online, false otherwise
   */
  static async isOnline(
    contextVariables: ThumbnailGenerationContextVariables
  ): Promise<boolean> {
    try {
      const { httpClient, thumbnailGenerationUrl } = contextVariables;
      const healthUrl = `${thumbnailGenerationUrl.replace(/\/$/, '')}/health`;

      await httpClient.get(healthUrl);
      return true;
    } catch {
      return false;
    }
  }
}
