name: Autogen

on:
  pull_request:
  push:
    branches: [main]

jobs:
  autogen-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5  # Updated to v5
        with:
          python-version: "3.11"

      - name: Install datamodel-code-generator
        run: |
          pip install datamodel-code-generator[http]

      - name: Run autogen commands
        run: |
          # Array of services and their corresponding output files
          declare -A SERVICES=(
            ["entitycore"]="entitycore.py"
            ["obi-one"]="obione.py"
            ["thumbnail-generation"]="thumbnail_generation.py"
          )

          for service in "${!SERVICES[@]}"; do
              # Set extra-fields parameter based on service
              if [[ "$service" == "obi-one" ]]; then
                  extra_fields="ignore"
              else
                  extra_fields="allow"
              fi

              datamodel-codegen \
                --enum-field-as-literal=all \
                --target-python-version=3.11 \
                --reuse-model \
                --field-constraints \
                --input-file-type=openapi \
                --output-model-type=pydantic_v2.BaseModel \
                --openapi-scopes {schemas,paths,parameters} \
                --use-standard-collections \
                --use-union-operator \
                --use-default-kwarg \
                --use-operation-id-as-name \
                --extra-fields=$extra_fields \
                --disable-timestamp \
                --strict-nullable \
                --url="https://staging.openbraininstitute.org/api/${service}/openapi.json" \
                --output="src/neuroagent/tools/autogenerated_types/${SERVICES[$service]}"
          done

      - name: Check for meaningful changes
        run: |
          # Check if there are any changes at all
          if ! git diff --quiet HEAD -- src/neuroagent/tools/autogenerated_types/; then
            echo "Autogenerated files are outdated."
            echo ""
            echo "Changed files:"

            # Get all changed files
            changed_files=$(git diff --name-only HEAD -- src/neuroagent/tools/autogenerated_types/)
            echo "$changed_files" | while read file; do
              echo "  - $file"
            done

            echo ""
            echo "Please run the autogen commands locally and commit the changes."
            echo ""
            echo "Run these commands:"
            echo ""

            # Recreate the commands only for changed files
            declare -A SERVICES=(
              ["entitycore"]="entitycore.py"
              ["obi-one"]="obione.py"
              ["thumbnail-generation"]="thumbnail_generation.py"
            )

            for service in "${!SERVICES[@]}"; do
                output_file="src/neuroagent/tools/autogenerated_types/${SERVICES[$service]}"

                # Check if this specific file has changes
                if echo "$changed_files" | grep -q "${SERVICES[$service]}"; then
                    if [[ "$service" == "obi-one" ]]; then
                        extra_fields="ignore"
                    else
                        extra_fields="allow"
                    fi

                    echo "# For ${SERVICES[$service]}:"
                    echo "datamodel-codegen \\"
                    echo "  --enum-field-as-literal=all \\"
                    echo "  --target-python-version=3.11 \\"
                    echo "  --reuse-model \\"
                    echo "  --field-constraints \\"
                    echo "  --input-file-type=openapi \\"
                    echo "  --output-model-type=pydantic_v2.BaseModel \\"
                    echo "  --openapi-scopes {schemas,paths,parameters} \\"
                    echo "  --use-standard-collections \\"
                    echo "  --use-union-operator \\"
                    echo "  --use-default-kwarg \\"
                    echo "  --use-operation-id-as-name \\"
                    echo "  --extra-fields=$extra_fields \\"
                    echo "  --disable-timestamp \\"
                    echo "  --strict-nullable \\"
                    echo "  --url=\"https://staging.openbraininstitute.org/api/${service}/openapi.json\" \\"
                    echo "  --output=\"$output_file\""
                    echo ""
                fi
            done

            exit 1
          else
            echo "No changes detected in autogenerated files."
          fi
