name: Autogen

on:
  pull_request:
  push:
    branches: [main]

jobs:
  autogen-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5  # Updated to v5
        with:
          python-version: "3.11"

      - name: Install datamodel-code-generator
        run: |
          pip install datamodel-code-generator[http]

      - name: Run autogen commands
        run: |
          # Array of services and their corresponding output files
          declare -A SERVICES=(
            ["entitycore"]="entitycore.py"
            ["obi-one"]="obione.py"
            ["bluenaas"]="bluenaas.py"
            ["thumbnail-generation"]="thumbnail_generation.py"
          )

          for service in "${!SERVICES[@]}"; do
              datamodel-codegen \
                --enum-field-as-literal=all \
                --target-python-version=3.11 \
                --reuse-model \
                --field-constraints \
                --input-file-type=openapi \
                --output-model-type=pydantic_v2.BaseModel \
                --openapi-scopes {schemas,paths,parameters} \
                --use-standard-collections \
                --use-union-operator \
                --use-default-kwarg \
                --use-operation-id-as-name \
                --extra-fields=allow \
                --url="https://staging.openbraininstitute.org/api/${service}/openapi.json" \
                --output="src/neuroagent/tools/autogenerated_types/${SERVICES[$service]}"
            done

      - name: Check for meaningful changes
        run: |
          # Check if there are any changes at all
          if ! git diff --quiet HEAD -- src/neuroagent/tools/autogenerated_types/; then
            # Filter out timestamp lines and diff headers
            FILTERED_DIFF=$(git diff HEAD -- src/neuroagent/tools/autogenerated_types/ | \
              grep -v '^[+-]#   timestamp:' | \
              grep -E '^[+-][^+-]' || true)

            if [ -n "$FILTERED_DIFF" ]; then
              echo "Autogenerated files are outdated."
              echo ""
              echo "Changed files:"

              # Get files with meaningful changes (not just timestamps)
              for file in $(git diff --name-only --relative HEAD -- src/neuroagent/tools/autogenerated_types/); do
                # Check if this specific file has non-timestamp changes
                FILE_CHANGES=$(git diff HEAD -- "$file" | \
                  grep -v '^[+-]#   timestamp:' | \
                  grep -E '^[+-][^+-]' || true)
                if [ -n "$FILE_CHANGES" ]; then
                  echo "  - $file"
                fi
              done

              echo ""
              echo "Please run the autogen commands locally and commit the changes."
              exit 1
            else
              echo "All autogenerated files are up to date."
            fi
          else
            echo "No changes detected in autogenerated files."
          fi
