name: Autogen

on:
  pull_request:
  push:
    branches: [main]

jobs:
  autogen-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5  # Updated to v5
        with:
          python-version: "3.11"

      - name: Install datamodel-code-generator
        run: |
          pip install datamodel-code-generator

      - name: Run autogen commands
        run: |
          # Define common parameters
          COMMON_ARGS="--enum-field-as-literal=all --target-python-version=3.11  --reuse-model  --field-constraints --input-file-type=openapi --output-model-type=pydantic_v2.BaseModel --openapi-scopes={schemas,paths,parameters} --use-standard-collections --use-union-operator --use-default-kwarg --use-operation-id-as-name --extra-fields=forbid"

          # Define base URL and output directory
          BASE_URL="https://staging.openbraininstitute.org/api"
          OUTPUT_DIR="src/neuroagent/tools/autogenerated_types"

          # Array of services and their corresponding output files
          declare -A SERVICES=(
            ["entitycore"]="entitycore.py"
            ["obi-one"]="obione.py"
            ["literature"]="literature.py"
            ["bluenaas"]="bluenaas.py"
            ["thumbnail-generation"]="thumbnail_generation.py"
          )

          # Run datamodel-codegen for each service
          for service in "${!SERVICES[@]}"; do
            echo $COMMON_ARGS
            echo datamodel-codegen $COMMON_ARGS \
              --url="${BASE_URL}/${service}/openapi.json" \
              --output="${OUTPUT_DIR}/${SERVICES[$service]}"
            datamodel-codegen $COMMON_ARGS \
              --url="${BASE_URL}/${service}/openapi.json" \
              --output="${OUTPUT_DIR}/${SERVICES[$service]}"
          done

      - name: Check for meaningful changes
        run: |
          # Check for changes excluding timestamp lines
          FILTERED_DIFF=$(git diff HEAD -- src/neuroagent/tools/autogenerated_types/ | \
            grep -v '^[+-]#   timestamp:' | \
            grep -E '^[+-]' | \
            grep -v '^[+-]{3}')

          if [ -n "$FILTERED_DIFF" ]; then
            echo "Autogenerated files are outdated"
            exit 1
          fi
